{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.69.jar",
          "url": "functional-test-api-0.0.0.69.jar",
          "size": 2016,
          "sha512": "9c92da5c35e06ce32022f4869c77a253d8c8e50ef77e0cbfd94720bc9c70a052ce62e424a29402b4b9249a54786f84de7fb9eefd456eb0b6d8baa2b9a6b0e45b",
          "sha256": "c8a162aaf5157c4e53841e36cc1f51800b597e6e4aaeb8ebdd0cdc5aa339b51f",
          "sha1": "e215729a3cadf1cb8d782365517fef041ad0f2ef",
          "md5": "5acba4a1f68c8ed427629507228b0942"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.69.jar",
          "url": "functional-test-api-0.0.0.69.jar",
          "size": 2016,
          "sha512": "9c92da5c35e06ce32022f4869c77a253d8c8e50ef77e0cbfd94720bc9c70a052ce62e424a29402b4b9249a54786f84de7fb9eefd456eb0b6d8baa2b9a6b0e45b",
          "sha256": "c8a162aaf5157c4e53841e36cc1f51800b597e6e4aaeb8ebdd0cdc5aa339b51f",
          "sha1": "e215729a3cadf1cb8d782365517fef041ad0f2ef",
          "md5": "5acba4a1f68c8ed427629507228b0942"
        }
      ]
    }
  ]
}
