{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.69.jar",
          "url": "functional-test-api-0.0.0.69.jar",
          "size": 2016,
          "sha512": "1668fd9dbd9ee8158caa3e031601f21480947da12750cb330832abece1777ceff8846ec049671f3cfd5e506a5c825f68831a77ff6e274510176c3316517c93d8",
          "sha256": "2967849f8cbe8c4756f972472d93004e5bcf1a56529c952cf049a2a0bd640a5b",
          "sha1": "5d49f375298526d64e02b04fa39ee763d321e276",
          "md5": "4055e72562b169dc8bc560d4c82ed47c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.69.jar",
          "url": "functional-test-api-0.0.0.69.jar",
          "size": 2016,
          "sha512": "1668fd9dbd9ee8158caa3e031601f21480947da12750cb330832abece1777ceff8846ec049671f3cfd5e506a5c825f68831a77ff6e274510176c3316517c93d8",
          "sha256": "2967849f8cbe8c4756f972472d93004e5bcf1a56529c952cf049a2a0bd640a5b",
          "sha1": "5d49f375298526d64e02b04fa39ee763d321e276",
          "md5": "4055e72562b169dc8bc560d4c82ed47c"
        }
      ]
    }
  ]
}
