{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-plugin",
    "version": "0.0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "k5i6tghx25edbcvkq7zp6kc2ii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-plugin-0.0.0.31.jar",
          "url": "risk-plugin-0.0.0.31.jar",
          "size": 66039,
          "sha512": "ae11a1b720272d4a1fbfe9d7477e6e424faa1e9a1342a4e9576f536b2d71ad89e0b867b78b2b53f5bd4292926fea8e125cae2eb596cb9cd0356db58c937aafcd",
          "sha256": "148f48e966199bc304686bbe826758ae3d4c097e690dc0aede0142c60318dc7b",
          "sha1": "006721093bfc2fb303906f20be051a202148934f",
          "md5": "850cbb0a94330e36e6c464bc84df9b80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.31"
          }
        },
        {
          "group": "setools",
          "module": "action-items-plugin",
          "version": {
            "requires": "0.0.0.31"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.31"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "[4.1.2,5.0.0)"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "risk-plugin-0.0.0.31.jar",
          "url": "risk-plugin-0.0.0.31.jar",
          "size": 66039,
          "sha512": "ae11a1b720272d4a1fbfe9d7477e6e424faa1e9a1342a4e9576f536b2d71ad89e0b867b78b2b53f5bd4292926fea8e125cae2eb596cb9cd0356db58c937aafcd",
          "sha256": "148f48e966199bc304686bbe826758ae3d4c097e690dc0aede0142c60318dc7b",
          "sha1": "006721093bfc2fb303906f20be051a202148934f",
          "md5": "850cbb0a94330e36e6c464bc84df9b80"
        }
      ]
    }
  ]
}
