{
  "formatVersion": "1.1",
  "component": {
    "group": "setools.api",
    "module": "gradle-utils",
    "version": "0.0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "rcg4wgw4hjgkfoacp4stqyeyym"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-utils-0.0.0.45.jar",
          "url": "gradle-utils-0.0.0.45.jar",
          "size": 1256,
          "sha512": "1dca118d9ae474fec6dbec2ad436bd9468dc1350bf77edb99e253a97e6fff3ac3ca24ec50025182d98f5359b9e6bf4ce1cde7fcee030b76c72dd73c26c09b3b1",
          "sha256": "fec61b528ebf2df21f6ff03110423510b85c722251f5d40d042d6503112fd92b",
          "sha1": "c5b13ccf398cf98c5de50def95b62e9d2f5033ba",
          "md5": "30e7a87c507794c0f4a79cdf3d6ded4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-utils-0.0.0.45.jar",
          "url": "gradle-utils-0.0.0.45.jar",
          "size": 1256,
          "sha512": "1dca118d9ae474fec6dbec2ad436bd9468dc1350bf77edb99e253a97e6fff3ac3ca24ec50025182d98f5359b9e6bf4ce1cde7fcee030b76c72dd73c26c09b3b1",
          "sha256": "fec61b528ebf2df21f6ff03110423510b85c722251f5d40d042d6503112fd92b",
          "sha1": "c5b13ccf398cf98c5de50def95b62e9d2f5033ba",
          "md5": "30e7a87c507794c0f4a79cdf3d6ded4d"
        }
      ]
    }
  ]
}
