{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "3hxchvadprgudef3zaokwxguni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.47"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.47.jar",
          "url": "sysml14-api-0.0.0.47.jar",
          "size": 4848,
          "sha512": "38c99ed53842c20a27bebe01de54394ae7918cc8a11ea2c3689a361d0f2e26ec400e34dec8e903dfa7a46c2ba0cf14cb263a8357012f6bc94542c9a946799bed",
          "sha256": "2d08c70d3052ef7a17b7a93c39924f0c2431303d829a2471c8bd565b1998c6db",
          "sha1": "54e3df4200fe98673e1e2d5fc596285774cf2873",
          "md5": "6b06ef567cc1fec3c5d2be919f81fdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.47"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.47.jar",
          "url": "sysml14-api-0.0.0.47.jar",
          "size": 4848,
          "sha512": "38c99ed53842c20a27bebe01de54394ae7918cc8a11ea2c3689a361d0f2e26ec400e34dec8e903dfa7a46c2ba0cf14cb263a8357012f6bc94542c9a946799bed",
          "sha256": "2d08c70d3052ef7a17b7a93c39924f0c2431303d829a2471c8bd565b1998c6db",
          "sha1": "54e3df4200fe98673e1e2d5fc596285774cf2873",
          "md5": "6b06ef567cc1fec3c5d2be919f81fdb"
        }
      ]
    }
  ]
}
