{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.70.jar",
          "url": "base-utils-0.0.0.70.jar",
          "size": 1196,
          "sha512": "e90612f758cbe642038d1d81d996d27fc701db046c800be7cedc4e2ea0a08fdca706c7772854ff0ae9b043d69475f7699373dde77f391a6fe8d81998d0a2bf7a",
          "sha256": "822b24b6b4d6c43f23294f34471814ed1c865b5ab51dcfe004a166b483159def",
          "sha1": "fc91cfc72e277b177e9befc7ceb39276b4b25daa",
          "md5": "72543c86d4d04f77bfa9823b4e74f9c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.70.jar",
          "url": "base-utils-0.0.0.70.jar",
          "size": 1196,
          "sha512": "e90612f758cbe642038d1d81d996d27fc701db046c800be7cedc4e2ea0a08fdca706c7772854ff0ae9b043d69475f7699373dde77f391a6fe8d81998d0a2bf7a",
          "sha256": "822b24b6b4d6c43f23294f34471814ed1c865b5ab51dcfe004a166b483159def",
          "sha1": "fc91cfc72e277b177e9befc7ceb39276b4b25daa",
          "md5": "72543c86d4d04f77bfa9823b4e74f9c2"
        }
      ]
    }
  ]
}
