{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "latex-risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.69.jar",
          "url": "latex-risk-review-plugin-0.0.0.69.jar",
          "size": 16967,
          "sha512": "f5935308b5f6a77bf2099dba1b83b9effd9966e8fcf7cc59731dc1df4f52de136ab0ddf795ed4170297942d8f4a9a2f18501b056925431f000bb3a12ce3d9312",
          "sha256": "fd18d0a3fbcfbec74ebadcd8698e8ac87b3f79199cd7cbf24c6fa551f565aa98",
          "sha1": "4964bd79f345ddc84f9bce8c9460d59e243e2d0e",
          "md5": "fd0d75db40d55fa4ee0aaa1f8c2952be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "base-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.69.jar",
          "url": "latex-risk-review-plugin-0.0.0.69.jar",
          "size": 16967,
          "sha512": "f5935308b5f6a77bf2099dba1b83b9effd9966e8fcf7cc59731dc1df4f52de136ab0ddf795ed4170297942d8f4a9a2f18501b056925431f000bb3a12ce3d9312",
          "sha256": "fd18d0a3fbcfbec74ebadcd8698e8ac87b3f79199cd7cbf24c6fa551f565aa98",
          "sha1": "4964bd79f345ddc84f9bce8c9460d59e243e2d0e",
          "md5": "fd0d75db40d55fa4ee0aaa1f8c2952be"
        }
      ]
    }
  ]
}
