{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "latex-risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.69.jar",
          "url": "latex-risk-review-plugin-0.0.0.69.jar",
          "size": 16967,
          "sha512": "cc297d42aa049603f39c500d931bb0a26a07499603462907c3c40905f8a863c1a88fff2907461a15ae2804e6d8aa04707e2a258c0c40d82545db81b8eed1cc24",
          "sha256": "762e1e62cf55a1e7fb62468f57e5cc9783baa95a6aaccfeed6d39775c3576f3c",
          "sha1": "ec93363269bd60ec047c681a9b7a797b9e887f4c",
          "md5": "387e5488b6021d66b86796dcdaa5172a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "base-utils",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.69.jar",
          "url": "latex-risk-review-plugin-0.0.0.69.jar",
          "size": 16967,
          "sha512": "cc297d42aa049603f39c500d931bb0a26a07499603462907c3c40905f8a863c1a88fff2907461a15ae2804e6d8aa04707e2a258c0c40d82545db81b8eed1cc24",
          "sha256": "762e1e62cf55a1e7fb62468f57e5cc9783baa95a6aaccfeed6d39775c3576f3c",
          "sha1": "ec93363269bd60ec047c681a9b7a797b9e887f4c",
          "md5": "387e5488b6021d66b86796dcdaa5172a"
        }
      ]
    }
  ]
}
