{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "boct5krlmzgqdadpxux4vy4nfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "c9efdd2794e311d80f85378418f49f85f8f9a5d27c4aedfd86c52a535d8e5861d3238242f85d0fb398f6d8b68d22ab60d42810e60837f29b897de1bbf758e30",
          "sha256": "1800a69efe7a4c4c91271589445fb6747fd5b0c7573ff289e469a8bfc0406b1f",
          "sha1": "ee461d9b1a68872ca6e72f85199398427b5c4bef",
          "md5": "f90435c4f9a17250b67253b8cbc297bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "c9efdd2794e311d80f85378418f49f85f8f9a5d27c4aedfd86c52a535d8e5861d3238242f85d0fb398f6d8b68d22ab60d42810e60837f29b897de1bbf758e30",
          "sha256": "1800a69efe7a4c4c91271589445fb6747fd5b0c7573ff289e469a8bfc0406b1f",
          "sha1": "ee461d9b1a68872ca6e72f85199398427b5c4bef",
          "md5": "f90435c4f9a17250b67253b8cbc297bc"
        }
      ]
    }
  ]
}
