{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "ddfb8c9f0ee0cd2d167921eb54bccd08d66f998566698a1348eeb31ba1d18cce82f7ab2b6c67ee0211f74915818a8f6d71fcae1006d4592257525cbde5a6ee0b",
          "sha256": "5d39a0a511df804c196a77bf3c34249b46f34243628e895962d58dd94161029f",
          "sha1": "9d0c66d33ebd0f6d59ca70c5f8e767f5a0958b81",
          "md5": "6408ad4d0c19bf11a7f735ad045a06c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "ddfb8c9f0ee0cd2d167921eb54bccd08d66f998566698a1348eeb31ba1d18cce82f7ab2b6c67ee0211f74915818a8f6d71fcae1006d4592257525cbde5a6ee0b",
          "sha256": "5d39a0a511df804c196a77bf3c34249b46f34243628e895962d58dd94161029f",
          "sha1": "9d0c66d33ebd0f6d59ca70c5f8e767f5a0958b81",
          "md5": "6408ad4d0c19bf11a7f735ad045a06c8"
        }
      ]
    }
  ]
}
