{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "1a4dc885df34ae5f0f077b661e0a0aaa2a2565d351792bb494b38df771404d33351990bb226cb202fc4b50a7fa090a4c1c52552a5c4377b3727f3ae424f61321",
          "sha256": "d6e2a188c182353b914dfba225697b821aef04fae5064d671c271f15a05f9aee",
          "sha1": "354b13f36fedbbf6b47bc8bbc9f8048a3a1dc82c",
          "md5": "d0f87937edbcca6d67ac6865a3952cb0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.69.jar",
          "url": "risk-management-plugin-0.0.0.69.jar",
          "size": 7335,
          "sha512": "1a4dc885df34ae5f0f077b661e0a0aaa2a2565d351792bb494b38df771404d33351990bb226cb202fc4b50a7fa090a4c1c52552a5c4377b3727f3ae424f61321",
          "sha256": "d6e2a188c182353b914dfba225697b821aef04fae5064d671c271f15a05f9aee",
          "sha1": "354b13f36fedbbf6b47bc8bbc9f8048a3a1dc82c",
          "md5": "d0f87937edbcca6d67ac6865a3952cb0"
        }
      ]
    }
  ]
}
