{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.69.jar",
          "url": "uml-plugin-0.0.0.69.jar",
          "size": 6132,
          "sha512": "6cc59515a80ea0a0b9e5a4d82ef6b95b2612429d4c72abd5f5220355b092612fad94e72ea3a02f4b1482e36d2a6daeaca6394c8b6154291f18cd2263e7f0b957",
          "sha256": "57d15c7ce76afe86021062c1e7b79ad168f1f632439abe4dad1688a596614538",
          "sha1": "16126259ed7e3138fcf592bca44011a5c2c1f9a0",
          "md5": "296492f67f0b2a49450cf1f8224969cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.69.jar",
          "url": "uml-plugin-0.0.0.69.jar",
          "size": 6132,
          "sha512": "6cc59515a80ea0a0b9e5a4d82ef6b95b2612429d4c72abd5f5220355b092612fad94e72ea3a02f4b1482e36d2a6daeaca6394c8b6154291f18cd2263e7f0b957",
          "sha256": "57d15c7ce76afe86021062c1e7b79ad168f1f632439abe4dad1688a596614538",
          "sha1": "16126259ed7e3138fcf592bca44011a5c2c1f9a0",
          "md5": "296492f67f0b2a49450cf1f8224969cd"
        }
      ]
    }
  ]
}
