{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.69.jar",
          "url": "uml-plugin-0.0.0.69.jar",
          "size": 6132,
          "sha512": "d82bb223ccc12093e867926b7ae758577f3fc10e772a7d8b1e01f44f0043dc951a3f08c10e7cbd1570c25b3b03b0484ba8c175daf582eaafd1278eee4eaf2e9d",
          "sha256": "e5d9daa5d7c1eb8ce7caa2ec411f669b4d8a4f7eb91822e3108e3197f71c1478",
          "sha1": "31416eefc3fedfb9d1faf4502c79ba96424f1a5c",
          "md5": "ce77f0c584ca4b98d4089b70b5c7c874"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.69.jar",
          "url": "uml-plugin-0.0.0.69.jar",
          "size": 6132,
          "sha512": "d82bb223ccc12093e867926b7ae758577f3fc10e772a7d8b1e01f44f0043dc951a3f08c10e7cbd1570c25b3b03b0484ba8c175daf582eaafd1278eee4eaf2e9d",
          "sha256": "e5d9daa5d7c1eb8ce7caa2ec411f669b4d8a4f7eb91822e3108e3197f71c1478",
          "sha1": "31416eefc3fedfb9d1faf4502c79ba96424f1a5c",
          "md5": "ce77f0c584ca4b98d4089b70b5c7c874"
        }
      ]
    }
  ]
}
