{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.68.jar",
          "url": "risk-review-plugin-0.0.0.68.jar",
          "size": 3744,
          "sha512": "6d7fc7dbed51571dad4139f6ec3db916b48561e9c7bef4dbbae42b6c6d618f19559bdb5bbabbe64c2285eb35bef306529a93c265677aa3b75832725a94c1fe9d",
          "sha256": "1988b6f68d3dc55f6e3ba065ed7faf6b3d74375e3cc70a4393d0dfe451e9c04d",
          "sha1": "7115a18af5947a8c3f2c0a3ce17e3885fd08dcec",
          "md5": "577a4d87c913c1afe6918e059038057"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.68.jar",
          "url": "risk-review-plugin-0.0.0.68.jar",
          "size": 3744,
          "sha512": "6d7fc7dbed51571dad4139f6ec3db916b48561e9c7bef4dbbae42b6c6d618f19559bdb5bbabbe64c2285eb35bef306529a93c265677aa3b75832725a94c1fe9d",
          "sha256": "1988b6f68d3dc55f6e3ba065ed7faf6b3d74375e3cc70a4393d0dfe451e9c04d",
          "sha1": "7115a18af5947a8c3f2c0a3ce17e3885fd08dcec",
          "md5": "577a4d87c913c1afe6918e059038057"
        }
      ]
    }
  ]
}
