{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.68.jar",
          "url": "risk-review-plugin-0.0.0.68.jar",
          "size": 3744,
          "sha512": "e8170a4c3ac46dc03f32a32f8e64564860dbbdf814f446da2a9ca98983caef7a1d9ea3d76d15587c264870b9edd33290c30875aaeced9d00de2b01ffbdf58df",
          "sha256": "b2e596f3c47e07439f1adf344fd9f95d7d80e91315d6e9d06b28c9d68c7670cc",
          "sha1": "4e2e9a1837fe8308c8c1d86ff61da300456822ad",
          "md5": "f9f506db66223580016ce5daa90b2de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.68.jar",
          "url": "risk-review-plugin-0.0.0.68.jar",
          "size": 3744,
          "sha512": "e8170a4c3ac46dc03f32a32f8e64564860dbbdf814f446da2a9ca98983caef7a1d9ea3d76d15587c264870b9edd33290c30875aaeced9d00de2b01ffbdf58df",
          "sha256": "b2e596f3c47e07439f1adf344fd9f95d7d80e91315d6e9d06b28c9d68c7670cc",
          "sha1": "4e2e9a1837fe8308c8c1d86ff61da300456822ad",
          "md5": "f9f506db66223580016ce5daa90b2de"
        }
      ]
    }
  ]
}
