{
  "formatVersion": "1.1",
  "component": {
    "group": "setools.plugins",
    "module": "aggregate-javadoc-plugin",
    "version": "0.0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "7sl2se4burdfji7eyi3e7sxmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "aggregate-javadoc-plugin-0.0.0.38.jar",
          "url": "aggregate-javadoc-plugin-0.0.0.38.jar",
          "size": 3332,
          "sha512": "20095debf8c7b8a807be75f277b1501338d84527b02351608d663b4d5bf9d6ff5c68f3e7da2663fe331ad8125f126f8807777116d6c717fe1db079fbb4621d5c",
          "sha256": "b016c84e6c02b7c82b886ee75d96be81b9ff19d7a9123bb34975acad4ce98a9a",
          "sha1": "d79d30282ebde349c94e2c4044db741ecba91f60",
          "md5": "38a442578bdd85c5b8201e611f0bf994"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools.api",
          "module": "gradle-utils",
          "version": {
            "requires": "0.0.0.38"
          }
        }
      ],
      "files": [
        {
          "name": "aggregate-javadoc-plugin-0.0.0.38.jar",
          "url": "aggregate-javadoc-plugin-0.0.0.38.jar",
          "size": 3332,
          "sha512": "20095debf8c7b8a807be75f277b1501338d84527b02351608d663b4d5bf9d6ff5c68f3e7da2663fe331ad8125f126f8807777116d6c717fe1db079fbb4621d5c",
          "sha256": "b016c84e6c02b7c82b886ee75d96be81b9ff19d7a9123bb34975acad4ce98a9a",
          "sha1": "d79d30282ebde349c94e2c4044db741ecba91f60",
          "md5": "38a442578bdd85c5b8201e611f0bf994"
        }
      ]
    }
  ]
}
