<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="risk" nsURI="http://setools/setools/risk/0.0.11/RiskML" nsPrefix="risk">
  <eClassifiers xsi:type="ecore:EClass" name="Risk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" ordered="false"
        lowerBound="1" eType="#//Likelihood"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consequence" ordered="false"
        lowerBound="1" eType="#//Consequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" ordered="false" lowerBound="1"
        eType="#//RiskLevel" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Likelihood">
    <eLiterals name="NOT_LIKELY"/>
    <eLiterals name="LOW_LIKELIHOOD" value="1"/>
    <eLiterals name="LIKELY" value="2"/>
    <eLiterals name="HIGHLY_LIKELY" value="3"/>
    <eLiterals name="NEAR_CERTAINTY" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Consequence">
    <eLiterals name="MINIMAL_IMPACT"/>
    <eLiterals name="LOW_IMPACT" value="1"/>
    <eLiterals name="MODERATE_IMPACT" value="2"/>
    <eLiterals name="SIGNIFICANT_IMPACT" value="3"/>
    <eLiterals name="CATASTROPHIC_IMPACT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RiskLevel">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Risk Level"/>
    </eAnnotations>
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RiskMitigation">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Risk Mitigation"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planned" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statement" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" ordered="false"
        lowerBound="1" eType="#//Likelihood"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consequence" ordered="false"
        lowerBound="1" eType="#//Consequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risk" ordered="false" lowerBound="1"
        eType="#//RiskLevel" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatusUpdate">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="Status Update"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
        eType="ecore:EClass ../../../../../org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
</ecore:EPackage>
