{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.70.jar",
          "url": "functional-test-api-0.0.0.70.jar",
          "size": 2016,
          "sha512": "66b644370899e31a9474693c67bef95912c7621617ca85ecd286a460f24bc2912056d8b55adcfc5173afda70bc6e9673af3be606ecab8cfeed08a9e0584e00de",
          "sha256": "e31f4fc5cad0a6793633844c7a3fad8cfbd3cb75576b6c64fa66092a066d7c29",
          "sha1": "80110ac72d05cf204c00402e1c405338a38ef11a",
          "md5": "d68d8907fea8f4443944a821e52e6468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.70.jar",
          "url": "functional-test-api-0.0.0.70.jar",
          "size": 2016,
          "sha512": "66b644370899e31a9474693c67bef95912c7621617ca85ecd286a460f24bc2912056d8b55adcfc5173afda70bc6e9673af3be606ecab8cfeed08a9e0584e00de",
          "sha256": "e31f4fc5cad0a6793633844c7a3fad8cfbd3cb75576b6c64fa66092a066d7c29",
          "sha1": "80110ac72d05cf204c00402e1c405338a38ef11a",
          "md5": "d68d8907fea8f4443944a821e52e6468"
        }
      ]
    }
  ]
}
