{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.69.jar",
          "url": "sysml16-api-0.0.0.69.jar",
          "size": 4846,
          "sha512": "7f7db7ebb2bd4ae5ebd53215e56d94b432c49d9a38afe69a35a520396d6f05034a1dcf244e1d92cf921f1de8c6ee166e011c0cb081dc6c9f4f96125b87aa0145",
          "sha256": "4e7cd2eefa43c539a9ca65fb1cb5b5a5bfd08679e50859029dbcf7ac936ef33e",
          "sha1": "7aea7ea68d77d809af8950a326c4d84b30fe1d6a",
          "md5": "bb8bf93cb9a15efc9e4f4059341284a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.69.jar",
          "url": "sysml16-api-0.0.0.69.jar",
          "size": 4846,
          "sha512": "7f7db7ebb2bd4ae5ebd53215e56d94b432c49d9a38afe69a35a520396d6f05034a1dcf244e1d92cf921f1de8c6ee166e011c0cb081dc6c9f4f96125b87aa0145",
          "sha256": "4e7cd2eefa43c539a9ca65fb1cb5b5a5bfd08679e50859029dbcf7ac936ef33e",
          "sha1": "7aea7ea68d77d809af8950a326c4d84b30fe1d6a",
          "md5": "bb8bf93cb9a15efc9e4f4059341284a8"
        }
      ]
    }
  ]
}
