{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.69.jar",
          "url": "sysml16-api-0.0.0.69.jar",
          "size": 4846,
          "sha512": "d785edda8a4b8a53ee330aed5add403a26cdf8a7c56b5b0ea0d110f7a5cc31a8a478fe1469414053f9b0bedd8adf734d074e9db057b3b66495a37c48cbef070b",
          "sha256": "c751e72176cfd6e10e8e5d46a19e6a6fea869f75aeb6eaec1f52966b03e29319",
          "sha1": "30ff300fffcae73d08d9adab48b8fe25992216c3",
          "md5": "6a8963f293e5c519117f92e30486707c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.69.jar",
          "url": "sysml16-api-0.0.0.69.jar",
          "size": 4846,
          "sha512": "d785edda8a4b8a53ee330aed5add403a26cdf8a7c56b5b0ea0d110f7a5cc31a8a478fe1469414053f9b0bedd8adf734d074e9db057b3b66495a37c48cbef070b",
          "sha256": "c751e72176cfd6e10e8e5d46a19e6a6fea869f75aeb6eaec1f52966b03e29319",
          "sha1": "30ff300fffcae73d08d9adab48b8fe25992216c3",
          "md5": "6a8963f293e5c519117f92e30486707c"
        }
      ]
    }
  ]
}
