{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "mbse-plugin",
    "version": "0.0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zfiazopo6vhiloqz7au766qqqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mbse-plugin-0.0.0.46.jar",
          "url": "mbse-plugin-0.0.0.46.jar",
          "size": 4186,
          "sha512": "251ceb28c61f0a17fe31e030e9685e615a3d067b7af5cd1c9f71378a1e4bb812e9c949804b6c0cfda5a4247ead8eaa8bbab656ab3385f49ead1520c14da8d1e3",
          "sha256": "0fb0c9badff2312542ceef7936ab4b265678012693ae63636a5e30d86a462c85",
          "sha1": "5f0edf80d8cc906bcfcbf3579b9d9890663dd087",
          "md5": "63a13d715a4a272ce2e8b74a76872c93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.46"
          }
        },
        {
          "group": "setools",
          "module": "risk-plugin",
          "version": {
            "requires": "0.0.0.46"
          }
        }
      ],
      "files": [
        {
          "name": "mbse-plugin-0.0.0.46.jar",
          "url": "mbse-plugin-0.0.0.46.jar",
          "size": 4186,
          "sha512": "251ceb28c61f0a17fe31e030e9685e615a3d067b7af5cd1c9f71378a1e4bb812e9c949804b6c0cfda5a4247ead8eaa8bbab656ab3385f49ead1520c14da8d1e3",
          "sha256": "0fb0c9badff2312542ceef7936ab4b265678012693ae63636a5e30d86a462c85",
          "sha1": "5f0edf80d8cc906bcfcbf3579b9d9890663dd087",
          "md5": "63a13d715a4a272ce2e8b74a76872c93"
        }
      ]
    }
  ]
}
