{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.70.jar",
          "url": "meetings-plugin-0.0.0.70.jar",
          "size": 92285,
          "sha512": "24a7706b735daad6509a5914557e567384e0135af91b1ac90836f7e26f9f9ff1a8a035e390b25841f4d26394f421cd55ce2dc8c9b0b0c607266160dfdb517fb8",
          "sha256": "8be1af95551eede2048e205988f2cecba49a03eb3420ca1576382fd18f030320",
          "sha1": "494df32d6114edae0a3d4f08d1f2ef2ec25c344e",
          "md5": "1f5726e71c3fa58714c22ecced10fafe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.70.jar",
          "url": "meetings-plugin-0.0.0.70.jar",
          "size": 92285,
          "sha512": "24a7706b735daad6509a5914557e567384e0135af91b1ac90836f7e26f9f9ff1a8a035e390b25841f4d26394f421cd55ce2dc8c9b0b0c607266160dfdb517fb8",
          "sha256": "8be1af95551eede2048e205988f2cecba49a03eb3420ca1576382fd18f030320",
          "sha1": "494df32d6114edae0a3d4f08d1f2ef2ec25c344e",
          "md5": "1f5726e71c3fa58714c22ecced10fafe"
        }
      ]
    }
  ]
}
