{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "size": 91587,
          "sha512": "8ac184b6c8723345484126b6405b27a52a012602265f37a68bbc770f9bfc7c4547c888fae4dfecbe2fdb753c238033b6765b3bc95405ce72221a7553a73ee516",
          "sha256": "962ac1669b30193329290e6f1392bf354288fb9e6b0da7d0715e33d4d81ca1b8",
          "sha1": "c2e887b91ed194f7e837413d75afc0ef1fe709a9",
          "md5": "ee14e30d5e51b5e608bd51f3fae8dbee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "size": 91587,
          "sha512": "8ac184b6c8723345484126b6405b27a52a012602265f37a68bbc770f9bfc7c4547c888fae4dfecbe2fdb753c238033b6765b3bc95405ce72221a7553a73ee516",
          "sha256": "962ac1669b30193329290e6f1392bf354288fb9e6b0da7d0715e33d4d81ca1b8",
          "sha1": "c2e887b91ed194f7e837413d75afc0ef1fe709a9",
          "md5": "ee14e30d5e51b5e608bd51f3fae8dbee"
        }
      ]
    }
  ]
}
