{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "size": 91587,
          "sha512": "e6ed800260a958cc4376fa59aee46a408380e1717a858d61740586b7a772780d1cefdf882950465236137f760779701bb44b08b274a85854888d655d07ef1c3a",
          "sha256": "d487ca22eac69a8c359a689475feffeecafd3bf553f77336af32bc27bbb4ebba",
          "sha1": "70666648682cc9e1549f212d60385cc14be61eed",
          "md5": "6a8247ba935cf3588d177093a4c6f07c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.69.jar",
          "size": 91587,
          "sha512": "e6ed800260a958cc4376fa59aee46a408380e1717a858d61740586b7a772780d1cefdf882950465236137f760779701bb44b08b274a85854888d655d07ef1c3a",
          "sha256": "d487ca22eac69a8c359a689475feffeecafd3bf553f77336af32bc27bbb4ebba",
          "sha1": "70666648682cc9e1549f212d60385cc14be61eed",
          "md5": "6a8247ba935cf3588d177093a4c6f07c"
        }
      ]
    }
  ]
}
