{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-plugin",
    "version": "0.0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "kwekce3gfjdwjn2c67vurmxcfm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-plugin-0.0.0.35.jar",
          "url": "risk-plugin-0.0.0.35.jar",
          "size": 65407,
          "sha512": "62efd895645b7d052eede3ab5ac8ba632df1a581b2b5102f04ac05bcd8958ca66e9707008155544c02ea9b75576ec666b4b0be50b1065fbaf7ab2b8974b27c06",
          "sha256": "f0a602d765ab7b6fe201a6200532506860bb850ed9a7c1e909ced79e2e0315a1",
          "sha1": "aff3a3f1efbbbcd8d9b03794f2b5326571ddd471",
          "md5": "2895fd7d9d28e21691ee4232e9db2d83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.35"
          }
        },
        {
          "group": "setools",
          "module": "action-items-plugin",
          "version": {
            "requires": "0.0.0.35"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.35"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "[4.1.2,5.0.0)"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "risk-plugin-0.0.0.35.jar",
          "url": "risk-plugin-0.0.0.35.jar",
          "size": 65407,
          "sha512": "62efd895645b7d052eede3ab5ac8ba632df1a581b2b5102f04ac05bcd8958ca66e9707008155544c02ea9b75576ec666b4b0be50b1065fbaf7ab2b8974b27c06",
          "sha256": "f0a602d765ab7b6fe201a6200532506860bb850ed9a7c1e909ced79e2e0315a1",
          "sha1": "aff3a3f1efbbbcd8d9b03794f2b5326571ddd471",
          "md5": "2895fd7d9d28e21691ee4232e9db2d83"
        }
      ]
    }
  ]
}
