{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gehbh7oo3fevlhipu7ewq4giua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.70.jar",
          "url": "uml-api-0.0.0.70.jar",
          "size": 4307,
          "sha512": "4c48f25244641ac0078e997592192717adec53118db621a87c4c241b49e2dad6a288108218331391ec47838933d37ccf0327b9220667e8e209f1c2fd8e9cd273",
          "sha256": "1c2c44bd8d1d1e8bdeb5c91987a194fc8b67fce4d3812ba51e6f4126b9d4cc47",
          "sha1": "da6ad1216a045d8f0953eeef9b5a858de601d994",
          "md5": "c7888e88f00e43c254c1351dbf9f8c3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.70.jar",
          "url": "uml-api-0.0.0.70.jar",
          "size": 4307,
          "sha512": "4c48f25244641ac0078e997592192717adec53118db621a87c4c241b49e2dad6a288108218331391ec47838933d37ccf0327b9220667e8e209f1c2fd8e9cd273",
          "sha256": "1c2c44bd8d1d1e8bdeb5c91987a194fc8b67fce4d3812ba51e6f4126b9d4cc47",
          "sha1": "da6ad1216a045d8f0953eeef9b5a858de601d994",
          "md5": "c7888e88f00e43c254c1351dbf9f8c3d"
        }
      ]
    }
  ]
}
