{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-plugin",
    "version": "0.0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "vafwkqsvzbdbpazcqygdehzzpa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-plugin-0.0.0.48.jar",
          "url": "risk-plugin-0.0.0.48.jar",
          "size": 76063,
          "sha512": "5d0d8ce06a4eeb9f288beb5052b0443764c86b2f9d080dcbe08dbb0819fb7f55fb2b5f47fc19db7c41c039a5a494db11044762014dc180c61e9be30b361293ac",
          "sha256": "31e7a89f1865b1f630c406bb74b960773e3de759b83be31ed6637f42065898df",
          "sha1": "7e48d0a730ee6d3f4959ad7cc711b5edaf366986",
          "md5": "d64f097c4c8152f9529a0edeedc9cb44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.48"
          }
        },
        {
          "group": "setools",
          "module": "action-items-plugin",
          "version": {
            "requires": "0.0.0.48"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.48"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "[4.1.2,5.0.0)"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "risk-plugin-0.0.0.48.jar",
          "url": "risk-plugin-0.0.0.48.jar",
          "size": 76063,
          "sha512": "5d0d8ce06a4eeb9f288beb5052b0443764c86b2f9d080dcbe08dbb0819fb7f55fb2b5f47fc19db7c41c039a5a494db11044762014dc180c61e9be30b361293ac",
          "sha256": "31e7a89f1865b1f630c406bb74b960773e3de759b83be31ed6637f42065898df",
          "sha1": "7e48d0a730ee6d3f4959ad7cc711b5edaf366986",
          "md5": "d64f097c4c8152f9529a0edeedc9cb44"
        }
      ]
    }
  ]
}
