{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.70.jar",
          "url": "risk-review-plugin-0.0.0.70.jar",
          "size": 3744,
          "sha512": "337c2094246176812638f94f036a20d47ed30f76685e0455131afcd153757f4c658f2ab6b2e4a90a5c88feeff6300368c84fe52aab5b4418c7f41fd90fa8c286",
          "sha256": "9f3e98cc1c704952a998369ee45cd50e1192d7574b9b8ddb2fca29aba0fe50d9",
          "sha1": "caa9f95e2f4df2a99e8854005bd6f7951c67bdae",
          "md5": "e12258579046ea44f04440ed70740359"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.70.jar",
          "url": "risk-review-plugin-0.0.0.70.jar",
          "size": 3744,
          "sha512": "337c2094246176812638f94f036a20d47ed30f76685e0455131afcd153757f4c658f2ab6b2e4a90a5c88feeff6300368c84fe52aab5b4418c7f41fd90fa8c286",
          "sha256": "9f3e98cc1c704952a998369ee45cd50e1192d7574b9b8ddb2fca29aba0fe50d9",
          "sha1": "caa9f95e2f4df2a99e8854005bd6f7951c67bdae",
          "md5": "e12258579046ea44f04440ed70740359"
        }
      ]
    }
  ]
}
