{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "gl32mala4vasviphtlu7xzwgby"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.41.jar",
          "url": "meetings-plugin-0.0.0.41.jar",
          "size": 90401,
          "sha512": "f889c172a30405979a49bf8b78366dd900d81b95c46615fe46c400b4dd678d1cc9203fc410a17359a916830512a7f0bbd48cc56ff7632274f80d810ff8c56ddf",
          "sha256": "590e94fd925f954eb9874eec96d72497e0708c715ade4a44c13502a48d0effde",
          "sha1": "1256fd644c4774b375bd0e92d95bd714c4486123",
          "md5": "1b8da9283fdbd34659cc3a28e03d6869"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.41.jar",
          "url": "meetings-plugin-0.0.0.41.jar",
          "size": 90401,
          "sha512": "f889c172a30405979a49bf8b78366dd900d81b95c46615fe46c400b4dd678d1cc9203fc410a17359a916830512a7f0bbd48cc56ff7632274f80d810ff8c56ddf",
          "sha256": "590e94fd925f954eb9874eec96d72497e0708c715ade4a44c13502a48d0effde",
          "sha1": "1256fd644c4774b375bd0e92d95bd714c4486123",
          "md5": "1b8da9283fdbd34659cc3a28e03d6869"
        }
      ]
    }
  ]
}
