{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "8c70b6944b2710ebaa84cc1fe79a3ea53fbd12d140a1888fd06f73a651282e48eb34acaef313e9ab8a749f975f5e15dbb74fdf013df4e55de7a8df3519223fb8",
          "sha256": "3d38bbfae801816c8a598bdf37cecec31e787588651900ac2e0ca82e74c926cb",
          "sha1": "2f70cc11d6c7903d0b463f96daf49178e1fe6583",
          "md5": "9c6274546cd91c2de576c905c0ec4a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "8c70b6944b2710ebaa84cc1fe79a3ea53fbd12d140a1888fd06f73a651282e48eb34acaef313e9ab8a749f975f5e15dbb74fdf013df4e55de7a8df3519223fb8",
          "sha256": "3d38bbfae801816c8a598bdf37cecec31e787588651900ac2e0ca82e74c926cb",
          "sha1": "2f70cc11d6c7903d0b463f96daf49178e1fe6583",
          "md5": "9c6274546cd91c2de576c905c0ec4a6"
        }
      ]
    }
  ]
}
