{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "533732f0053a636741855a2beaf4a2605b09389c360e280c203e5fa2009aeafc96ea8322beecf8267cfdc9efcf6eecdd8352d99dfbfaade620f08b9c663b03c5",
          "sha256": "93e7fdbc216c06c2201de0902b37a56c39c370ffa29fc12181a6ab5f7a86a837",
          "sha1": "91611c8b461f52892e39cd8dd20d0a36c46fbb8f",
          "md5": "e2e1694f317c28d3ed4c73f3649f5213"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "533732f0053a636741855a2beaf4a2605b09389c360e280c203e5fa2009aeafc96ea8322beecf8267cfdc9efcf6eecdd8352d99dfbfaade620f08b9c663b03c5",
          "sha256": "93e7fdbc216c06c2201de0902b37a56c39c370ffa29fc12181a6ab5f7a86a837",
          "sha1": "91611c8b461f52892e39cd8dd20d0a36c46fbb8f",
          "md5": "e2e1694f317c28d3ed4c73f3649f5213"
        }
      ]
    }
  ]
}
