{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "e1aa6e6fdd548b87433cef6e9b5cb78df90eca09c46add39ac953bf90e53cd326f4647caaae4a4db3c4e8ff13d0ed4cdb34997936d365a63b811ca40f1e34e56",
          "sha256": "d32bf42306c3760db63f0376fe836bed508bbf97cce527250e2c6aa6da545df8",
          "sha1": "b8fc91c0200d74584d579b1a3425eaf44ba519ea",
          "md5": "2884160f51c9adc9a77f6ae8da785921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.68.jar",
          "url": "base-utils-0.0.0.68.jar",
          "size": 1196,
          "sha512": "e1aa6e6fdd548b87433cef6e9b5cb78df90eca09c46add39ac953bf90e53cd326f4647caaae4a4db3c4e8ff13d0ed4cdb34997936d365a63b811ca40f1e34e56",
          "sha256": "d32bf42306c3760db63f0376fe836bed508bbf97cce527250e2c6aa6da545df8",
          "sha1": "b8fc91c0200d74584d579b1a3425eaf44ba519ea",
          "md5": "2884160f51c9adc9a77f6ae8da785921"
        }
      ]
    }
  ]
}
