{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "53bca2c184091d1743886c7a68eec20a166189a638ca640b26fb7cf6bf433c7dd4c08ea7aef0d410867795a7169e9b7599e11e96ebdbd8dabad5d14bfe7c2ddb",
          "sha256": "3f06b398dec842dbc4dc0fe603fc3c5a3f64853ccc3ae8833ee92eeccf24c3a1",
          "sha1": "99aafc7245c5a51bdc77eaa1db96562a3b30699",
          "md5": "6c46af4c6c96d0bf10024b0bcd3ca3da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "53bca2c184091d1743886c7a68eec20a166189a638ca640b26fb7cf6bf433c7dd4c08ea7aef0d410867795a7169e9b7599e11e96ebdbd8dabad5d14bfe7c2ddb",
          "sha256": "3f06b398dec842dbc4dc0fe603fc3c5a3f64853ccc3ae8833ee92eeccf24c3a1",
          "sha1": "99aafc7245c5a51bdc77eaa1db96562a3b30699",
          "md5": "6c46af4c6c96d0bf10024b0bcd3ca3da"
        }
      ]
    }
  ]
}
