{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "2a23fea896840c6c0f45f067cbf32d6a47f63995b9393f4313dca3ae01a720bc5e0618d1bf16683c29dd68d9a625d38525a0f5431c24470c25802bb709abdfe7",
          "sha256": "c9cdb51357c1955d1e190f66f5028f7f3bbf8161f9bb2527f53ae9df733ddf78",
          "sha1": "55e779f0c0748e57fe04115ada5544768261663c",
          "md5": "f99538cc28c56ae29d09242240f75193"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "2a23fea896840c6c0f45f067cbf32d6a47f63995b9393f4313dca3ae01a720bc5e0618d1bf16683c29dd68d9a625d38525a0f5431c24470c25802bb709abdfe7",
          "sha256": "c9cdb51357c1955d1e190f66f5028f7f3bbf8161f9bb2527f53ae9df733ddf78",
          "sha1": "55e779f0c0748e57fe04115ada5544768261663c",
          "md5": "f99538cc28c56ae29d09242240f75193"
        }
      ]
    }
  ]
}
