{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "47003b2b919cb6589dfeb4012e23359fd746b862e9160a3b91070cf2a4fbd0fcae899ee933fec84360290430b578bfee179e05803b391770bc77a9e4c1cd8895",
          "sha256": "961922f6ccd28d8a64c5e4d963b1915b689f6d5e4efac7a86d3767fbbe4710e8",
          "sha1": "ebf2536f2823d434fcc17313862b19e1f445b331",
          "md5": "55a2de19122c719677d47e088f11deb9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.68.jar",
          "url": "uml-plugin-0.0.0.68.jar",
          "size": 6132,
          "sha512": "47003b2b919cb6589dfeb4012e23359fd746b862e9160a3b91070cf2a4fbd0fcae899ee933fec84360290430b578bfee179e05803b391770bc77a9e4c1cd8895",
          "sha256": "961922f6ccd28d8a64c5e4d963b1915b689f6d5e4efac7a86d3767fbbe4710e8",
          "sha1": "ebf2536f2823d434fcc17313862b19e1f445b331",
          "md5": "55a2de19122c719677d47e088f11deb9"
        }
      ]
    }
  ]
}
