{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "mbse-plugin",
    "version": "0.0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "ckq5abcvkrdjvdjs2dseaa7fju"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mbse-plugin-0.0.0.28.jar",
          "url": "mbse-plugin-0.0.0.28.jar",
          "size": 1599,
          "sha512": "a3d3f9db1d68c0a4bf21667d75c0f7cdc94bcb1f9bc40a304fc15367dd9f147f44f0311d0a97ea4749cedbc5e1ac1bb04c98b0b8d16324eaed3a6f2dbfa042cc",
          "sha256": "5939264599f00db0343067dfa4f5cfc6586b1b4bceb9cb506bf3adc0aef9cdf1",
          "sha1": "f0a0cbdfa51457f3d66a27f31f80435aa72f9c0d",
          "md5": "61716eec62441cc15b311d68fcfe2950"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mbse-plugin-0.0.0.28.jar",
          "url": "mbse-plugin-0.0.0.28.jar",
          "size": 1599,
          "sha512": "a3d3f9db1d68c0a4bf21667d75c0f7cdc94bcb1f9bc40a304fc15367dd9f147f44f0311d0a97ea4749cedbc5e1ac1bb04c98b0b8d16324eaed3a6f2dbfa042cc",
          "sha256": "5939264599f00db0343067dfa4f5cfc6586b1b4bceb9cb506bf3adc0aef9cdf1",
          "sha1": "f0a0cbdfa51457f3d66a27f31f80435aa72f9c0d",
          "md5": "61716eec62441cc15b311d68fcfe2950"
        }
      ]
    }
  ]
}
