{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-plugin",
    "version": "0.0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "igidnqsaxreink5koyvwdv2ism"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-plugin-0.0.0.34.jar",
          "url": "risk-plugin-0.0.0.34.jar",
          "size": 65407,
          "sha512": "9ffb83ba14a6b6c4b00892a8918aadcad8c52ba3bfebfe17c3f3ca08f2b2bf80bf6c90cc03ec118330aa286e91d21e36fe630b93836b925d7b6b2f303d53a363",
          "sha256": "a3c9fcfd58e7ff91ca41ab9bfee2af97c5ade8f8b40bf01ed71fb19c45d27603",
          "sha1": "a787ee8f27e529265c466cbffa4568650c11a1e0",
          "md5": "79eb89e9e354ab4ecdca498a41353b50"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.34"
          }
        },
        {
          "group": "setools",
          "module": "action-items-plugin",
          "version": {
            "requires": "0.0.0.34"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.34"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "[4.1.2,5.0.0)"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "risk-plugin-0.0.0.34.jar",
          "url": "risk-plugin-0.0.0.34.jar",
          "size": 65407,
          "sha512": "9ffb83ba14a6b6c4b00892a8918aadcad8c52ba3bfebfe17c3f3ca08f2b2bf80bf6c90cc03ec118330aa286e91d21e36fe630b93836b925d7b6b2f303d53a363",
          "sha256": "a3c9fcfd58e7ff91ca41ab9bfee2af97c5ade8f8b40bf01ed71fb19c45d27603",
          "sha1": "a787ee8f27e529265c466cbffa4568650c11a1e0",
          "md5": "79eb89e9e354ab4ecdca498a41353b50"
        }
      ]
    }
  ]
}
