{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jddj4ba5krf4zb6n7fcoknt5yi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.49.jar",
          "url": "uml-api-0.0.0.49.jar",
          "size": 2780,
          "sha512": "2eecfd2148b5bce73085deef7e3d2ded89c31959d654da2e2d97c9d405fc6b3304d5df3ff0f21908f6c18b97ac8197ac0ed6cd905e274503044d576c979f1f90",
          "sha256": "2c280f0bfd041ce7a5fa004cebcc5e6dd415792b301e2fe05514768065e02b17",
          "sha1": "c7a65d826e15aceebe47ba67094208c1ca28a704",
          "md5": "34e5b61b2a950ac8752b71491c13549b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.49.jar",
          "url": "uml-api-0.0.0.49.jar",
          "size": 2780,
          "sha512": "2eecfd2148b5bce73085deef7e3d2ded89c31959d654da2e2d97c9d405fc6b3304d5df3ff0f21908f6c18b97ac8197ac0ed6cd905e274503044d576c979f1f90",
          "sha256": "2c280f0bfd041ce7a5fa004cebcc5e6dd415792b301e2fe05514768065e02b17",
          "sha1": "c7a65d826e15aceebe47ba67094208c1ca28a704",
          "md5": "34e5b61b2a950ac8752b71491c13549b"
        }
      ]
    }
  ]
}
