{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-base-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.69.jar",
          "url": "risk-base-plugin-0.0.0.69.jar",
          "size": 2682,
          "sha512": "9737922b4ddbd3bdd26b82c2e46ed21b1716f17414fcf9c9fdff5ff6b040dcb85834c8cc5a09eec744a1ab47d1aa5a1db00be0bd85eb1ed041e28eb9c206036f",
          "sha256": "4d391d95aa62648eccf7913da89721551c8c4bf2a7c964a089b8f8e82bc89603",
          "sha1": "2269e8fe1239d4b20c963f85b7758369f13e0812",
          "md5": "5804dfd704c231bc5f209cdbb6df18fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.69.jar",
          "url": "risk-base-plugin-0.0.0.69.jar",
          "size": 2682,
          "sha512": "9737922b4ddbd3bdd26b82c2e46ed21b1716f17414fcf9c9fdff5ff6b040dcb85834c8cc5a09eec744a1ab47d1aa5a1db00be0bd85eb1ed041e28eb9c206036f",
          "sha256": "4d391d95aa62648eccf7913da89721551c8c4bf2a7c964a089b8f8e82bc89603",
          "sha1": "2269e8fe1239d4b20c963f85b7758369f13e0812",
          "md5": "5804dfd704c231bc5f209cdbb6df18fe"
        }
      ]
    }
  ]
}
