{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-base-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.69.jar",
          "url": "risk-base-plugin-0.0.0.69.jar",
          "size": 2682,
          "sha512": "64a04735b6b632af9864c5dbf84b34fd65e495d5358673207a04bfccce699bc1869a60c57b1eab65b74d8ba7c85ca91362b02a20ab7f7938dbdb5af88bf37236",
          "sha256": "bfaa87f8ac10027f0171f8d217c3629c8726288a84af4866501c0b5fec214b7d",
          "sha1": "a495756be82f487c48f3bfa6d3e66aaa589001a8",
          "md5": "ebdaaf4a2f25449d6b78d8b7db015f0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.69.jar",
          "url": "risk-base-plugin-0.0.0.69.jar",
          "size": 2682,
          "sha512": "64a04735b6b632af9864c5dbf84b34fd65e495d5358673207a04bfccce699bc1869a60c57b1eab65b74d8ba7c85ca91362b02a20ab7f7938dbdb5af88bf37236",
          "sha256": "bfaa87f8ac10027f0171f8d217c3629c8726288a84af4866501c0b5fec214b7d",
          "sha1": "a495756be82f487c48f3bfa6d3e66aaa589001a8",
          "md5": "ebdaaf4a2f25449d6b78d8b7db015f0a"
        }
      ]
    }
  ]
}
