{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "3hxchvadprgudef3zaokwxguni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.47"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.47.jar",
          "url": "sysml16-api-0.0.0.47.jar",
          "size": 4846,
          "sha512": "127be64ead83260c0b30707e582b28ffd11ddfdd1e5ca13b03ca2816f5f6bce1a7af579917b05a21e04a846abf72009822a5b2c2495b5e15bd6edc223c050ec7",
          "sha256": "b4410d6e419a45d8ae8b42ef1a96c087b8ce3ce218e3119dab9443dc36f7887b",
          "sha1": "e7faf12a8a7205187bd6f7a351833b596fcad51e",
          "md5": "b9eee9ce91f610a0f84673b5c0919fec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.47"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.47.jar",
          "url": "sysml16-api-0.0.0.47.jar",
          "size": 4846,
          "sha512": "127be64ead83260c0b30707e582b28ffd11ddfdd1e5ca13b03ca2816f5f6bce1a7af579917b05a21e04a846abf72009822a5b2c2495b5e15bd6edc223c050ec7",
          "sha256": "b4410d6e419a45d8ae8b42ef1a96c087b8ce3ce218e3119dab9443dc36f7887b",
          "sha1": "e7faf12a8a7205187bd6f7a351833b596fcad51e",
          "md5": "b9eee9ce91f610a0f84673b5c0919fec"
        }
      ]
    }
  ]
}
