{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "794174393039b9655421164263bfa0e7fe2f6d309b6f40ac6e7091b2520907042603498af94de7a64611182fed56d083084a81d751d10058dfd91b8df4eff8d9",
          "sha256": "138d30beb599831d1c5ff07e3e3032fab988aab9da17bea37268477e94506203",
          "sha1": "386f55353f6f0356222ffc04c4acfdabe14a62fb",
          "md5": "711f35af3946081cf5b2004ad90e1e07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "794174393039b9655421164263bfa0e7fe2f6d309b6f40ac6e7091b2520907042603498af94de7a64611182fed56d083084a81d751d10058dfd91b8df4eff8d9",
          "sha256": "138d30beb599831d1c5ff07e3e3032fab988aab9da17bea37268477e94506203",
          "sha1": "386f55353f6f0356222ffc04c4acfdabe14a62fb",
          "md5": "711f35af3946081cf5b2004ad90e1e07"
        }
      ]
    }
  ]
}
