{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "boct5krlmzgqdadpxux4vy4nfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "90d6bc1040c497314baee800aa550b5bd4bea964454e820320e8acecef18f549ca51ecf9dbf9858201acd82a4efcfd95130a9e7eab5d14e1579f2b406bf62856",
          "sha256": "cf527b525a166b62b80b0e3d367c8fe9e963cd68891787f93367f43ab86fd2af",
          "sha1": "97dfb70da2c1f3f6861a473f1c5691b72341bd4",
          "md5": "1cfc78fc1bcf838ccd951d82fdb17a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "90d6bc1040c497314baee800aa550b5bd4bea964454e820320e8acecef18f549ca51ecf9dbf9858201acd82a4efcfd95130a9e7eab5d14e1579f2b406bf62856",
          "sha256": "cf527b525a166b62b80b0e3d367c8fe9e963cd68891787f93367f43ab86fd2af",
          "sha1": "97dfb70da2c1f3f6861a473f1c5691b72341bd4",
          "md5": "1cfc78fc1bcf838ccd951d82fdb17a0"
        }
      ]
    }
  ]
}
