{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "4f6f207d8855c6ce857fedb058af977ca849c4ca79e4c9dfa0851544a7e10c437fdc5a9773eef73960417358ba2d6d62d6ac2447aa927bd1673a5550e54f6caf",
          "sha256": "b857bac5c1819bd14a62c63cbf5fd60ca7e3d248f3d582c553207d5f7b82d5ee",
          "sha1": "5fb6cb3b6a788ed944bd1fda2d201096647e3409",
          "md5": "46f1ba7b1395cc47839769ab38b082cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.69.jar",
          "url": "uml-api-0.0.0.69.jar",
          "size": 4307,
          "sha512": "4f6f207d8855c6ce857fedb058af977ca849c4ca79e4c9dfa0851544a7e10c437fdc5a9773eef73960417358ba2d6d62d6ac2447aa927bd1673a5550e54f6caf",
          "sha256": "b857bac5c1819bd14a62c63cbf5fd60ca7e3d248f3d582c553207d5f7b82d5ee",
          "sha1": "5fb6cb3b6a788ed944bd1fda2d201096647e3409",
          "md5": "46f1ba7b1395cc47839769ab38b082cb"
        }
      ]
    }
  ]
}
