{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7xxns67nsvewfpuupao4xeuumy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.71.jar",
          "url": "uml-api-0.0.0.71.jar",
          "size": 4307,
          "sha512": "85bad9fd415e6e8dd2dba6f7379aa11ced84ec3827afb93b7ea8cec8a0dd805a0425739cc184f17c611bb07702a2edd4725d8c88b7560281b11ff0680503cb33",
          "sha256": "9f738965078fad627ffa75c9133ab7622bb52fd8bd551ecf222575c2c0e1b409",
          "sha1": "1db839a2f112c9471ebe2c883f8d77c0a19cf7e2",
          "md5": "7b3134d0452c1d59dfcb4dea3a39c43b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.71.jar",
          "url": "uml-api-0.0.0.71.jar",
          "size": 4307,
          "sha512": "85bad9fd415e6e8dd2dba6f7379aa11ced84ec3827afb93b7ea8cec8a0dd805a0425739cc184f17c611bb07702a2edd4725d8c88b7560281b11ff0680503cb33",
          "sha256": "9f738965078fad627ffa75c9133ab7622bb52fd8bd551ecf222575c2c0e1b409",
          "sha1": "1db839a2f112c9471ebe2c883f8d77c0a19cf7e2",
          "md5": "7b3134d0452c1d59dfcb4dea3a39c43b"
        }
      ]
    }
  ]
}
