{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "ef12833ba092327d6a51033887522df741306e224c5214287d167c0f8e593b9bf4798a4732fa0fa2f2472d1c077e3bf714c2015b3b3963e453fd314740e8c463",
          "sha256": "e0e7e65541505e11f325e629386477114724126c963cc55b53020145dd9eff90",
          "sha1": "7b727721363340c3265552a4bb305c0a06f69614",
          "md5": "deaa9b4446d5c40cdc3807a46d579ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "ef12833ba092327d6a51033887522df741306e224c5214287d167c0f8e593b9bf4798a4732fa0fa2f2472d1c077e3bf714c2015b3b3963e453fd314740e8c463",
          "sha256": "e0e7e65541505e11f325e629386477114724126c963cc55b53020145dd9eff90",
          "sha1": "7b727721363340c3265552a4bb305c0a06f69614",
          "md5": "deaa9b4446d5c40cdc3807a46d579ae"
        }
      ]
    }
  ]
}
