{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "b0e402dee6b74fcba763ced0110b22352d06d3d1adc7f1ab8e9fa41dcd7497f4eb5f5fcf3ec395707b0e402a1290374bd475b5689463173ffcc120bcace9c4fa",
          "sha256": "577bbbba3c70e562a3ac094e93d08e988df06c155c2ae49d39776dd2175dec07",
          "sha1": "7ccf34bae5dfa820d5e1f330a41ffc192277cf8a",
          "md5": "c9f28e36c2cd1ae0bfe5adb21a59b6c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "b0e402dee6b74fcba763ced0110b22352d06d3d1adc7f1ab8e9fa41dcd7497f4eb5f5fcf3ec395707b0e402a1290374bd475b5689463173ffcc120bcace9c4fa",
          "sha256": "577bbbba3c70e562a3ac094e93d08e988df06c155c2ae49d39776dd2175dec07",
          "sha1": "7ccf34bae5dfa820d5e1f330a41ffc192277cf8a",
          "md5": "c9f28e36c2cd1ae0bfe5adb21a59b6c0"
        }
      ]
    }
  ]
}
