{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "functional-test-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "32773d5c2d4b31e8d259d18f7c9fb9e7bbff556aaa0f0f23a301ecae3f0f9dd4529dddd47c3a4538012831de23ac473d0e5285cd51d72d6339a2e572f7859062",
          "sha256": "21857444253441459f5a3c0a8101673e655ee52865b49a29658835499d3460bc",
          "sha1": "939a4f6d72a9b4fe5015ebb6375f7f759da52097",
          "md5": "55076b3e216fd0b158e99bffa8994589"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "classpath-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "functional-test-api-0.0.0.68.jar",
          "url": "functional-test-api-0.0.0.68.jar",
          "size": 2016,
          "sha512": "32773d5c2d4b31e8d259d18f7c9fb9e7bbff556aaa0f0f23a301ecae3f0f9dd4529dddd47c3a4538012831de23ac473d0e5285cd51d72d6339a2e572f7859062",
          "sha256": "21857444253441459f5a3c0a8101673e655ee52865b49a29658835499d3460bc",
          "sha1": "939a4f6d72a9b4fe5015ebb6375f7f759da52097",
          "md5": "55076b3e216fd0b158e99bffa8994589"
        }
      ]
    }
  ]
}
