{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "modeling",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modeling-0.0.0.69.jar",
          "url": "modeling-0.0.0.69.jar",
          "size": 261,
          "sha512": "502bca4e9cc7c495fd8d1058f4b979e8eb31ee91d11f1433c842fda58f0554d0c5636b4f9f1ee012b52c7d693f11eb8822db90a974b85df87c9d219a29388c50",
          "sha256": "cc2e6ba0ba741252c5c4adcc892cb8d94707486c53e42d2ed9201e319ac7ee79",
          "sha1": "2342ccb667db05a776fd9e6fec3fd948a8c3dd81",
          "md5": "beed556f5830519f457d79781a56278b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "modeling-0.0.0.69.jar",
          "url": "modeling-0.0.0.69.jar",
          "size": 261,
          "sha512": "502bca4e9cc7c495fd8d1058f4b979e8eb31ee91d11f1433c842fda58f0554d0c5636b4f9f1ee012b52c7d693f11eb8822db90a974b85df87c9d219a29388c50",
          "sha256": "cc2e6ba0ba741252c5c4adcc892cb8d94707486c53e42d2ed9201e319ac7ee79",
          "sha1": "2342ccb667db05a776fd9e6fec3fd948a8c3dd81",
          "md5": "beed556f5830519f457d79781a56278b"
        }
      ]
    }
  ]
}
