{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "modeling",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modeling-0.0.0.69.jar",
          "url": "modeling-0.0.0.69.jar",
          "size": 261,
          "sha512": "382e1a91c8172bec4a7fce6a09375c870508dce2e0a92f8a2dd36c3d0bf998931cdacbc3d24d0bab6b0e6c98185073198a7f8e948eb3ccd2400c7b16fa60f0ee",
          "sha256": "68fdcc44d0cac3f1ccafa90fd7b6cfd8a759d0660aa46d0b85cf5c1e3f50781e",
          "sha1": "e185d4459a77b45d0f360a4979b141b611b5f41d",
          "md5": "6f11ba5ec42466f3a42e25668b8df30e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "modeling-0.0.0.69.jar",
          "url": "modeling-0.0.0.69.jar",
          "size": 261,
          "sha512": "382e1a91c8172bec4a7fce6a09375c870508dce2e0a92f8a2dd36c3d0bf998931cdacbc3d24d0bab6b0e6c98185073198a7f8e948eb3ccd2400c7b16fa60f0ee",
          "sha256": "68fdcc44d0cac3f1ccafa90fd7b6cfd8a759d0660aa46d0b85cf5c1e3f50781e",
          "sha1": "e185d4459a77b45d0f360a4979b141b611b5f41d",
          "md5": "6f11ba5ec42466f3a42e25668b8df30e"
        }
      ]
    }
  ]
}
