{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "9014c55bdd0645f1bbb48d100a2624565cc57b6a7596e663534316c3a0ce4fb07d1ee8877a78f947dc1c7e0a8f6d965556ab9a03549d4df42394daec4e51e0e7",
          "sha256": "7449163b307e7469355995b0323bb7e0165258eaa9fb9a07bf365b7d88efa7f4",
          "sha1": "d914c17249ae35826df61faa3b59d09be64dcd86",
          "md5": "5271a07b0f1b69f8df686468cf3a6b29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "9014c55bdd0645f1bbb48d100a2624565cc57b6a7596e663534316c3a0ce4fb07d1ee8877a78f947dc1c7e0a8f6d965556ab9a03549d4df42394daec4e51e0e7",
          "sha256": "7449163b307e7469355995b0323bb7e0165258eaa9fb9a07bf365b7d88efa7f4",
          "sha1": "d914c17249ae35826df61faa3b59d09be64dcd86",
          "md5": "5271a07b0f1b69f8df686468cf3a6b29"
        }
      ]
    }
  ]
}
