{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "cd9d153d56e60b31f9c4887a90aa7a4d5a61e4747c05ecbfbbc59a0c95461f2ede23f9e0680cb1cc2974c5eebb49f52172bb92ae234af1282d431e3324ec3de",
          "sha256": "20b376bd7ed0b3ee524844b424e67f0931b00fad27271a021ab636c2b772a7b0",
          "sha1": "d68ad6bb8e5fc3f10c4b85192930c4eb02118d11",
          "md5": "759779e13b7d3c5711ffa4de07e5b08"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "cd9d153d56e60b31f9c4887a90aa7a4d5a61e4747c05ecbfbbc59a0c95461f2ede23f9e0680cb1cc2974c5eebb49f52172bb92ae234af1282d431e3324ec3de",
          "sha256": "20b376bd7ed0b3ee524844b424e67f0931b00fad27271a021ab636c2b772a7b0",
          "sha1": "d68ad6bb8e5fc3f10c4b85192930c4eb02118d11",
          "md5": "759779e13b7d3c5711ffa4de07e5b08"
        }
      ]
    }
  ]
}
