{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "96794fcdad2122c1241ad799df1e4dd4d9f4e32bb6e707ebbcbe283feac20c330917c28715432c110e623017efbc081d664a85d617611f472e608126ec1b1e01",
          "sha256": "553cb001e851341c0df83fc7df83a9f971f90b0f3b76ff7e433123226667fda3",
          "sha1": "166aa74021d5659d2f16a82d5d5e6f4426234afe",
          "md5": "15f85a990546415b1bcbd0a3586cd7ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.68.jar",
          "url": "sysml14-api-0.0.0.68.jar",
          "size": 4848,
          "sha512": "96794fcdad2122c1241ad799df1e4dd4d9f4e32bb6e707ebbcbe283feac20c330917c28715432c110e623017efbc081d664a85d617611f472e608126ec1b1e01",
          "sha256": "553cb001e851341c0df83fc7df83a9f971f90b0f3b76ff7e433123226667fda3",
          "sha1": "166aa74021d5659d2f16a82d5d5e6f4426234afe",
          "md5": "15f85a990546415b1bcbd0a3586cd7ec"
        }
      ]
    }
  ]
}
