{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 91101,
          "sha512": "cd8801023516013d96e77c88acdf6294da7e80be41126b960528564221e4d66e1cac30e5f15ba18348c6e3be61314e30ba88a3fa3c19356a2952bbca7949b851",
          "sha256": "d242d440fec9b11c44152a9cf6569722cd2c86f9dc8e574395629d9b503a86d4",
          "sha1": "5f23e065b7c9fcd67b22c59d6ce9d194f5a7e87d",
          "md5": "1ab2b5619c1b29cdf6ff47a3ad8bbd04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 91101,
          "sha512": "cd8801023516013d96e77c88acdf6294da7e80be41126b960528564221e4d66e1cac30e5f15ba18348c6e3be61314e30ba88a3fa3c19356a2952bbca7949b851",
          "sha256": "d242d440fec9b11c44152a9cf6569722cd2c86f9dc8e574395629d9b503a86d4",
          "sha1": "5f23e065b7c9fcd67b22c59d6ce9d194f5a7e87d",
          "md5": "1ab2b5619c1b29cdf6ff47a3ad8bbd04"
        }
      ]
    }
  ]
}
