{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 91069,
          "sha512": "a2fd9263fbbc2ebb9b318f9cb150976d52543ca07b01bdfe2de861fb10adad4560946afd0961a70499d97c749e7939e3ba70699f14891609ca1a9f1c3ce8fd1a",
          "sha256": "39082d645b3ba212526526da04f693cd7e63592d1d679c6a45fc4da2f76383d1",
          "sha1": "25e33a5e85d8e5372c0c08dc0b0f88d24d085d2a",
          "md5": "b173ad3693c8b3dc6c32cc9344ecdf9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 91069,
          "sha512": "a2fd9263fbbc2ebb9b318f9cb150976d52543ca07b01bdfe2de861fb10adad4560946afd0961a70499d97c749e7939e3ba70699f14891609ca1a9f1c3ce8fd1a",
          "sha256": "39082d645b3ba212526526da04f693cd7e63592d1d679c6a45fc4da2f76383d1",
          "sha1": "25e33a5e85d8e5372c0c08dc0b0f88d24d085d2a",
          "md5": "b173ad3693c8b3dc6c32cc9344ecdf9"
        }
      ]
    }
  ]
}
