{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 92108,
          "sha512": "3e9c41516d7f05e51057b6373ff7af9ab822a9aace66ad34ba1bd1ea9dd8588599567b162a9f0167a6ca0366684fbf8c0cb6d5e5c422de54aa0de689d2d8efe1",
          "sha256": "66e768d0c0b2f0e729667555919c46148829824713f87aa502fc418aed52dc3d",
          "sha1": "ea2c197af9b68743a0424511bae8e3161318827a",
          "md5": "42389c8a34d8294585e84c31b4afaeac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.68.jar",
          "url": "meetings-plugin-0.0.0.68.jar",
          "size": 92108,
          "sha512": "3e9c41516d7f05e51057b6373ff7af9ab822a9aace66ad34ba1bd1ea9dd8588599567b162a9f0167a6ca0366684fbf8c0cb6d5e5c422de54aa0de689d2d8efe1",
          "sha256": "66e768d0c0b2f0e729667555919c46148829824713f87aa502fc418aed52dc3d",
          "sha1": "ea2c197af9b68743a0424511bae8e3161318827a",
          "md5": "42389c8a34d8294585e84c31b4afaeac"
        }
      ]
    }
  ]
}
