{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-base-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.68.jar",
          "url": "risk-base-plugin-0.0.0.68.jar",
          "size": 2682,
          "sha512": "bdb82fb5bf59afe75feedd201152a802986960568c6d35fed4630c7fa128f1989ee533d293120aef278a93a54b48171cfc354d6c1603c72b19b6fd14381f5447",
          "sha256": "a128d0888b528cc7c7e94c860cd62b340e5c10417309840946fcfdfa020ed024",
          "sha1": "634a536a0bac85ae517e32426de3c05cb51c7114",
          "md5": "3647010d992b60efb66ced6ce4336c77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.68.jar",
          "url": "risk-base-plugin-0.0.0.68.jar",
          "size": 2682,
          "sha512": "bdb82fb5bf59afe75feedd201152a802986960568c6d35fed4630c7fa128f1989ee533d293120aef278a93a54b48171cfc354d6c1603c72b19b6fd14381f5447",
          "sha256": "a128d0888b528cc7c7e94c860cd62b340e5c10417309840946fcfdfa020ed024",
          "sha1": "634a536a0bac85ae517e32426de3c05cb51c7114",
          "md5": "3647010d992b60efb66ced6ce4336c77"
        }
      ]
    }
  ]
}
