{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-base-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.68.jar",
          "url": "risk-base-plugin-0.0.0.68.jar",
          "size": 2682,
          "sha512": "c29621582462d998215c159802706a2d495350c94fab7dbaa4a3ad3208d056e97ef6b719e4130785f48ae82a76627b5eeaa70b94803f2e44f86cecd4586eea83",
          "sha256": "b6e029056c8d9cae0bb7c286f04681bb207acc433e70c055ac9cc9b90b831588",
          "sha1": "13b1fafced04ea822dbad63618a9a31e00d81d85",
          "md5": "1591c20d98d450ea0c04633fae3d6c6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-base-plugin-0.0.0.68.jar",
          "url": "risk-base-plugin-0.0.0.68.jar",
          "size": 2682,
          "sha512": "c29621582462d998215c159802706a2d495350c94fab7dbaa4a3ad3208d056e97ef6b719e4130785f48ae82a76627b5eeaa70b94803f2e44f86cecd4586eea83",
          "sha256": "b6e029056c8d9cae0bb7c286f04681bb207acc433e70c055ac9cc9b90b831588",
          "sha1": "13b1fafced04ea822dbad63618a9a31e00d81d85",
          "md5": "1591c20d98d450ea0c04633fae3d6c6b"
        }
      ]
    }
  ]
}
