{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jddj4ba5krf4zb6n7fcoknt5yi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.49.jar",
          "url": "classpath-utils-0.0.0.49.jar",
          "size": 2930,
          "sha512": "86b8842258b08fedead8e3b2aaad5f0b6fe479b5d70a692485d3861277308dc16d2dd3d5acd91fcba9d506089f976e81da58252e3ca67632aaf12913812a932e",
          "sha256": "fd5cbcfffa132c318b76af650bcf9548875a9729bfd5928d5fbd2f2bffc234be",
          "sha1": "d2e50d413a984d113d7acd4b01221ca3ee79c3af",
          "md5": "29562044a50336c093159904bb13a6f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.49.jar",
          "url": "classpath-utils-0.0.0.49.jar",
          "size": 2930,
          "sha512": "86b8842258b08fedead8e3b2aaad5f0b6fe479b5d70a692485d3861277308dc16d2dd3d5acd91fcba9d506089f976e81da58252e3ca67632aaf12913812a932e",
          "sha256": "fd5cbcfffa132c318b76af650bcf9548875a9729bfd5928d5fbd2f2bffc234be",
          "sha1": "d2e50d413a984d113d7acd4b01221ca3ee79c3af",
          "md5": "29562044a50336c093159904bb13a6f9"
        }
      ]
    }
  ]
}
