{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "latex-risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.68.jar",
          "url": "latex-risk-review-plugin-0.0.0.68.jar",
          "size": 16967,
          "sha512": "5731cf885c60b902684a239dfbd56f744390f006501df6b4a23fb917e03a0087b1ed4053b44580843a85ba1cf9050f26d6d6c29b6e958fefc3e8ae443854a6f3",
          "sha256": "a1e1e48efb5e5f0afd3dca3907b18fc682432fd594724a6fae140602e708817e",
          "sha1": "389d7cae99a2a9616631910650964e502f9b2e43",
          "md5": "b39552fa814b8280be79d73a402656db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "base-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.68.jar",
          "url": "latex-risk-review-plugin-0.0.0.68.jar",
          "size": 16967,
          "sha512": "5731cf885c60b902684a239dfbd56f744390f006501df6b4a23fb917e03a0087b1ed4053b44580843a85ba1cf9050f26d6d6c29b6e958fefc3e8ae443854a6f3",
          "sha256": "a1e1e48efb5e5f0afd3dca3907b18fc682432fd594724a6fae140602e708817e",
          "sha1": "389d7cae99a2a9616631910650964e502f9b2e43",
          "md5": "b39552fa814b8280be79d73a402656db"
        }
      ]
    }
  ]
}
