{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "latex-risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.68.jar",
          "url": "latex-risk-review-plugin-0.0.0.68.jar",
          "size": 16967,
          "sha512": "14d7259c9cdbc05ab5f5e0c733f8e1d7a7a4195237e70b490a8035e8926e750415fb6cb2012cfdf6b82bad65040eac69a29e1b4e5be540b6ab62e63bdef74004",
          "sha256": "14d213038cfd032e77811bc78dd64423fb7d6b75fd2330dc96326ff44a16d5bb",
          "sha1": "a8eb7a12c7d8d510c26999ff6be2c55b8dc85a6f",
          "md5": "c49006e6234777e7a15b5898b9cee49d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "base-utils",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.velocity",
          "module": "velocity",
          "version": {
            "requires": "1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "latex-risk-review-plugin-0.0.0.68.jar",
          "url": "latex-risk-review-plugin-0.0.0.68.jar",
          "size": 16967,
          "sha512": "14d7259c9cdbc05ab5f5e0c733f8e1d7a7a4195237e70b490a8035e8926e750415fb6cb2012cfdf6b82bad65040eac69a29e1b4e5be540b6ab62e63bdef74004",
          "sha256": "14d213038cfd032e77811bc78dd64423fb7d6b75fd2330dc96326ff44a16d5bb",
          "sha1": "a8eb7a12c7d8d510c26999ff6be2c55b8dc85a6f",
          "md5": "c49006e6234777e7a15b5898b9cee49d"
        }
      ]
    }
  ]
}
