{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "boct5krlmzgqdadpxux4vy4nfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "cd44ebbe41e8601fb5634124a356ee3136cadb2cb35512acac6d4e11ba43e0d003b9ab74077ce4d9ea42e3a477f5817ab0168134785d9519be0f3a0a740afb06",
          "sha256": "40d685e5bf410ce9ed424e0862bfe34467eaec2d3146f21efe7a4d478148b4c5",
          "sha1": "29fe838478a5984e14ccf9617f617cd67f1cfbd2",
          "md5": "a3e74b97736042de44538bcb9652dcc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "cd44ebbe41e8601fb5634124a356ee3136cadb2cb35512acac6d4e11ba43e0d003b9ab74077ce4d9ea42e3a477f5817ab0168134785d9519be0f3a0a740afb06",
          "sha256": "40d685e5bf410ce9ed424e0862bfe34467eaec2d3146f21efe7a4d478148b4c5",
          "sha1": "29fe838478a5984e14ccf9617f617cd67f1cfbd2",
          "md5": "a3e74b97736042de44538bcb9652dcc5"
        }
      ]
    }
  ]
}
