{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "675e874e40b507f9be91981c0a9535c1d8a9477ca79098d6826563804caa3de983f58122e9292d0d5500884353152861c30f8bdc9184c90f1f7f69269e448aaf",
          "sha256": "8cb95bfa49c8d11bbdd4e609c0e5b03fcb348bf569aae6325614e97b8a638646",
          "sha1": "eef82c6b619c7d679610a1a5fbda5cbd53e94ca5",
          "md5": "bc73b278241077c3c5100cdbed1c58d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "675e874e40b507f9be91981c0a9535c1d8a9477ca79098d6826563804caa3de983f58122e9292d0d5500884353152861c30f8bdc9184c90f1f7f69269e448aaf",
          "sha256": "8cb95bfa49c8d11bbdd4e609c0e5b03fcb348bf569aae6325614e97b8a638646",
          "sha1": "eef82c6b619c7d679610a1a5fbda5cbd53e94ca5",
          "md5": "bc73b278241077c3c5100cdbed1c58d"
        }
      ]
    }
  ]
}
