{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "base-utils",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "65cc7ef0a821d1c221a784ae85ac38a0cdd64f9158107c876f070a16d0338eddbe848e33554f9a2e57c7d4bae8fc4db5f4fe9403f873aba769b9a3a529b19cd0",
          "sha256": "3b6c386936dccfc43332a0a85dc49f2ff615a0c89f207962c756054133b3a27d",
          "sha1": "648ec4554cce73b8e44a72b33ddcb99650b175c4",
          "md5": "b63578cf1b46d071dda1b18ed27c8d80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base-utils-0.0.0.69.jar",
          "url": "base-utils-0.0.0.69.jar",
          "size": 1196,
          "sha512": "65cc7ef0a821d1c221a784ae85ac38a0cdd64f9158107c876f070a16d0338eddbe848e33554f9a2e57c7d4bae8fc4db5f4fe9403f873aba769b9a3a529b19cd0",
          "sha256": "3b6c386936dccfc43332a0a85dc49f2ff615a0c89f207962c756054133b3a27d",
          "sha1": "648ec4554cce73b8e44a72b33ddcb99650b175c4",
          "md5": "b63578cf1b46d071dda1b18ed27c8d80"
        }
      ]
    }
  ]
}
