{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "smr5unupa5drrjbz25yk6ludie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.50"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.50.jar",
          "url": "sysml14-api-0.0.0.50.jar",
          "size": 4848,
          "sha512": "b5c997f7acf38e33c4284b0e38fe3d38b5a60db06d2525e37c310788f74ab56c355e053a9aef86f2b1e4fd1a9e731699d6e5ec20c0903c0e579da6dc15fa6a69",
          "sha256": "c4a581cd81f675cf4a8d701443d22bafe2acf7f740d0131a29403ee380b9eae1",
          "sha1": "fef743a57be2145017be83274a18cd66cd53a080",
          "md5": "3dbcbc4707a1e51d83b2728de35e35b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.50"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.50.jar",
          "url": "sysml14-api-0.0.0.50.jar",
          "size": 4848,
          "sha512": "b5c997f7acf38e33c4284b0e38fe3d38b5a60db06d2525e37c310788f74ab56c355e053a9aef86f2b1e4fd1a9e731699d6e5ec20c0903c0e579da6dc15fa6a69",
          "sha256": "c4a581cd81f675cf4a8d701443d22bafe2acf7f740d0131a29403ee380b9eae1",
          "sha1": "fef743a57be2145017be83274a18cd66cd53a080",
          "md5": "3dbcbc4707a1e51d83b2728de35e35b4"
        }
      ]
    }
  ]
}
