{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-plugin",
    "version": "0.0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zfiazopo6vhiloqz7au766qqqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-plugin-0.0.0.46.jar",
          "url": "risk-plugin-0.0.0.46.jar",
          "size": 76063,
          "sha512": "ed710827f094d8f25d2c74db326418228aae0b7cb3961f8bc01b1328d51f4d3274576f25262b6326b45b03922c026626b31a0f88b99552749e753bb7c7326c82",
          "sha256": "a287967015dfbd87225920ba2d15d1ae5703df45380467e0c289dfe140266920",
          "sha1": "2a98e4032ec80be92130b4b7a5000f30434cd9ea",
          "md5": "65f83ec4ea1f9b7d25aba561f7af87dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.46"
          }
        },
        {
          "group": "setools",
          "module": "action-items-plugin",
          "version": {
            "requires": "0.0.0.46"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.46"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "[4.1.2,5.0.0)"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "risk-plugin-0.0.0.46.jar",
          "url": "risk-plugin-0.0.0.46.jar",
          "size": 76063,
          "sha512": "ed710827f094d8f25d2c74db326418228aae0b7cb3961f8bc01b1328d51f4d3274576f25262b6326b45b03922c026626b31a0f88b99552749e753bb7c7326c82",
          "sha256": "a287967015dfbd87225920ba2d15d1ae5703df45380467e0c289dfe140266920",
          "sha1": "2a98e4032ec80be92130b4b7a5000f30434cd9ea",
          "md5": "65f83ec4ea1f9b7d25aba561f7af87dd"
        }
      ]
    }
  ]
}
