{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.68.jar",
          "url": "risk-api-0.0.0.68.jar",
          "size": 52213,
          "sha512": "b595640b1386aad81ab43bcb4000701bd1d7cc9ab0f1e3644f4f097486f182074aebbce0622935f86c242e0d622f5f20381e91a779804403d5b91c04ab99631a",
          "sha256": "bd17753fa13d0950158a0c25d491d0414e405063cd672412b05f1c8db88eaf44",
          "sha1": "23f23bc432a6453ce56d5e8a5552468a251c0864",
          "md5": "ac207f45cadb20954752a34201a9b4d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.68.jar",
          "url": "risk-api-0.0.0.68.jar",
          "size": 52213,
          "sha512": "b595640b1386aad81ab43bcb4000701bd1d7cc9ab0f1e3644f4f097486f182074aebbce0622935f86c242e0d622f5f20381e91a779804403d5b91c04ab99631a",
          "sha256": "bd17753fa13d0950158a0c25d491d0414e405063cd672412b05f1c8db88eaf44",
          "sha1": "23f23bc432a6453ce56d5e8a5552468a251c0864",
          "md5": "ac207f45cadb20954752a34201a9b4d8"
        }
      ]
    }
  ]
}
