{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.68.jar",
          "url": "risk-api-0.0.0.68.jar",
          "size": 52213,
          "sha512": "aed2717fcf3ea398284da8d341f45018a0bcb4d56ca6ab8fec9f178abb4ccd4aada22b196e812663c91094a3f45723892e42d8de99055931f79b4acef8933734",
          "sha256": "6f7294e905496b0d61b4be0d58c6aa8b1fdc67dfe93113dda056f665c92cb68d",
          "sha1": "49b4ac20da1f7c0d1c87c5c207b969101699a7bb",
          "md5": "fe00a0a85e1ce7557d1511d3ad59b55e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.68.jar",
          "url": "risk-api-0.0.0.68.jar",
          "size": 52213,
          "sha512": "aed2717fcf3ea398284da8d341f45018a0bcb4d56ca6ab8fec9f178abb4ccd4aada22b196e812663c91094a3f45723892e42d8de99055931f79b4acef8933734",
          "sha256": "6f7294e905496b0d61b4be0d58c6aa8b1fdc67dfe93113dda056f665c92cb68d",
          "sha1": "49b4ac20da1f7c0d1c87c5c207b969101699a7bb",
          "md5": "fe00a0a85e1ce7557d1511d3ad59b55e"
        }
      ]
    }
  ]
}
