{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "monte-carlo-api",
    "version": "0.0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "zfiazopo6vhiloqz7au766qqqa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.sf.mpxj",
          "module": "mpxj",
          "version": {
            "requires": "[8.3.2,9.0.0)"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "[3.6.1,4.0.0)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "monte-carlo-api-0.0.0.46.jar",
          "url": "monte-carlo-api-0.0.0.46.jar",
          "size": 9121,
          "sha512": "be0acf57362417d893266edea48f8881f009cfd27c2037f4c49c439afc5aa28b6e4b20059180726cd1ce880647c42e43a1a1213164f3c20d159089db5b4c603c",
          "sha256": "de184e302eadf24eff49adc4743f02b488fc292ee812ab8a31324a25c02e2217",
          "sha1": "23ff377f973da07e0de2b9c54149d7521ecde957",
          "md5": "db4a393e6922c2120b6fefe4946a1777"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.mpxj",
          "module": "mpxj",
          "version": {
            "requires": "[8.3.2,9.0.0)"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "[3.6.1,4.0.0)"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.7"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.7"
          }
        }
      ],
      "files": [
        {
          "name": "monte-carlo-api-0.0.0.46.jar",
          "url": "monte-carlo-api-0.0.0.46.jar",
          "size": 9121,
          "sha512": "be0acf57362417d893266edea48f8881f009cfd27c2037f4c49c439afc5aa28b6e4b20059180726cd1ce880647c42e43a1a1213164f3c20d159089db5b4c603c",
          "sha256": "de184e302eadf24eff49adc4743f02b488fc292ee812ab8a31324a25c02e2217",
          "sha1": "23ff377f973da07e0de2b9c54149d7521ecde957",
          "md5": "db4a393e6922c2120b6fefe4946a1777"
        }
      ]
    }
  ]
}
