{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7xxns67nsvewfpuupao4xeuumy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.71"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.71.jar",
          "url": "risk-api-0.0.0.71.jar",
          "size": 52213,
          "sha512": "e30aefde167adc7d176441c83d6c8f79c774c163c2351c3061725cce487186d5ec3f6110a3147d9188fb7a8bf4fbe75f352849ffb6768472a55f6631bcff514b",
          "sha256": "5079bddf78ecf0e13b05b7c7d74d6eca81ed750551c37993329b6d861391c968",
          "sha1": "ae808fbc87a221f59bb528220d24e8e12bea8259",
          "md5": "cdc96052a2073e15095dc0d5c2d848d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.71"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.71.jar",
          "url": "risk-api-0.0.0.71.jar",
          "size": 52213,
          "sha512": "e30aefde167adc7d176441c83d6c8f79c774c163c2351c3061725cce487186d5ec3f6110a3147d9188fb7a8bf4fbe75f352849ffb6768472a55f6631bcff514b",
          "sha256": "5079bddf78ecf0e13b05b7c7d74d6eca81ed750551c37993329b6d861391c968",
          "sha1": "ae808fbc87a221f59bb528220d24e8e12bea8259",
          "md5": "cdc96052a2073e15095dc0d5c2d848d7"
        }
      ]
    }
  ]
}
