{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "modeling",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "39f98645169a27e8e38265d364ffb069690e772b95f435e9dac7b24fb9ceb207b5a7f25fc8c01da32ee123472822215f0a48b09642bb4961225264cc898237a0",
          "sha256": "8c602277ef1dc10412b869c9acf926f0478c45dbd2599289bd40e9ec077004ca",
          "sha1": "ab577b5a2cc9123f8edeb317c2522d2bf8e390bb",
          "md5": "333a7768a5dd18d5a9e26a0f4754acf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "39f98645169a27e8e38265d364ffb069690e772b95f435e9dac7b24fb9ceb207b5a7f25fc8c01da32ee123472822215f0a48b09642bb4961225264cc898237a0",
          "sha256": "8c602277ef1dc10412b869c9acf926f0478c45dbd2599289bd40e9ec077004ca",
          "sha1": "ab577b5a2cc9123f8edeb317c2522d2bf8e390bb",
          "md5": "333a7768a5dd18d5a9e26a0f4754acf4"
        }
      ]
    }
  ]
}
