{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "modeling",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "901f899863f623afe5d4ddcd47f243e3010917fe0e8a0c0702ea164b2d746838921823fde6637b8d6562f0b0b97df15cd001f354c99ce2d51418beb003bdacb0",
          "sha256": "a99c867d0cbcdd449c3e3b107c6f579cf9d1e2e768480fd4995b3f04726fa316",
          "sha1": "68c09b582832e14c93ddfbdd0845178fc004bbb6",
          "md5": "ac5db7e0baad62359c354b20449a004f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "901f899863f623afe5d4ddcd47f243e3010917fe0e8a0c0702ea164b2d746838921823fde6637b8d6562f0b0b97df15cd001f354c99ce2d51418beb003bdacb0",
          "sha256": "a99c867d0cbcdd449c3e3b107c6f579cf9d1e2e768480fd4995b3f04726fa316",
          "sha1": "68c09b582832e14c93ddfbdd0845178fc004bbb6",
          "md5": "ac5db7e0baad62359c354b20449a004f"
        }
      ]
    }
  ]
}
