{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "modeling",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "b7dbe80b7eec82ed61cc2ba286a7233a9428c298da36bfa037b76f12d519b84e81c9b986d5f797d0dfed933d0ee139a2d9e410f838b1b1de310aefd7cf3a1b7c",
          "sha256": "7937d6cca463003c479ec649ce3b05ddbfc23173aff9b11ca826144b35d50f5a",
          "sha1": "3c6dff249f6bbb5abf0d5759b347e179a9856c4",
          "md5": "1f75ae98c6f0631ec42d5c38bebc6457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "modeling-0.0.0.68.jar",
          "url": "modeling-0.0.0.68.jar",
          "size": 261,
          "sha512": "b7dbe80b7eec82ed61cc2ba286a7233a9428c298da36bfa037b76f12d519b84e81c9b986d5f797d0dfed933d0ee139a2d9e410f838b1b1de310aefd7cf3a1b7c",
          "sha256": "7937d6cca463003c479ec649ce3b05ddbfc23173aff9b11ca826144b35d50f5a",
          "sha1": "3c6dff249f6bbb5abf0d5759b347e179a9856c4",
          "md5": "1f75ae98c6f0631ec42d5c38bebc6457"
        }
      ]
    }
  ]
}
