{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jddj4ba5krf4zb6n7fcoknt5yi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.49"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.49.jar",
          "url": "risk-api-0.0.0.49.jar",
          "size": 44063,
          "sha512": "4de7b15c107f6b572d7314c47efb928c576ce3af66ad106b3865b44c7b32fd29d9b60002a6774904154aa9ace88a10fb8dde982a2a517916c9e2c94b76e7d3bb",
          "sha256": "5c6e9445f996f46e730b686bd8f07384af3c20081e9e5a1ff4079136e7e5e0d2",
          "sha1": "10d9129a7ce9c384ad1773514c17da60d9d610d3",
          "md5": "d0827c53bc6aea701979a74cb01b2264"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.49"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.49.jar",
          "url": "risk-api-0.0.0.49.jar",
          "size": 44063,
          "sha512": "4de7b15c107f6b572d7314c47efb928c576ce3af66ad106b3865b44c7b32fd29d9b60002a6774904154aa9ace88a10fb8dde982a2a517916c9e2c94b76e7d3bb",
          "sha256": "5c6e9445f996f46e730b686bd8f07384af3c20081e9e5a1ff4079136e7e5e0d2",
          "sha1": "10d9129a7ce9c384ad1773514c17da60d9d610d3",
          "md5": "d0827c53bc6aea701979a74cb01b2264"
        }
      ]
    }
  ]
}
