{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "92dda0ac021a0734612aa09f460e4e060414b54c1a093f46c4b2d610cc9b4fc8ec391ff2d9381ffadaf1f0480c66133d04a9dfb7a520c96d0fe321b42978cbc3",
          "sha256": "152305222cf34fac0fe64274d10bd2d13febe98bd02c74a93af252ab7bd3f389",
          "sha1": "1a78749d8936ede7bc01a8c1b4aa330b288e11e5",
          "md5": "48b7561c26e93b572408a3d247053ed0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "92dda0ac021a0734612aa09f460e4e060414b54c1a093f46c4b2d610cc9b4fc8ec391ff2d9381ffadaf1f0480c66133d04a9dfb7a520c96d0fe321b42978cbc3",
          "sha256": "152305222cf34fac0fe64274d10bd2d13febe98bd02c74a93af252ab7bd3f389",
          "sha1": "1a78749d8936ede7bc01a8c1b4aa330b288e11e5",
          "md5": "48b7561c26e93b572408a3d247053ed0"
        }
      ]
    }
  ]
}
