{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "1ba18023ca186ca7bfe54dfc25bac3403f434e24e080394309c2c492224bf86017066e108beb87ab2874c2711c7ebac8c7225d76f87688c83f05f6b2eea382e1",
          "sha256": "6a860906148723b76560f46b8f5526f2a2e32081dd89caeed69a2050e97e6ee6",
          "sha1": "36afbe9a91c6f7efd53afd7b6ef69d4027ebb280",
          "md5": "17dbc57ce8f913f3b0effea34d04f41c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "1ba18023ca186ca7bfe54dfc25bac3403f434e24e080394309c2c492224bf86017066e108beb87ab2874c2711c7ebac8c7225d76f87688c83f05f6b2eea382e1",
          "sha256": "6a860906148723b76560f46b8f5526f2a2e32081dd89caeed69a2050e97e6ee6",
          "sha1": "36afbe9a91c6f7efd53afd7b6ef69d4027ebb280",
          "md5": "17dbc57ce8f913f3b0effea34d04f41c"
        }
      ]
    }
  ]
}
