{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "f07f6f08cb999984ad23aec2196b6ff2a0795d82d865a6dae3bb33d1288654316d0ed1641395b9853b400dddc803b8de6bae66d33847e31b3f0fb533415a6457",
          "sha256": "ffad5687cc57b3558217e7c941b5c5ad00ba39165b55e0a923ae0aec512cb815",
          "sha1": "b55a7cece87704c40a96bc00cec912b6be0f1343",
          "md5": "255bcaec0aa50b37e2f27a52bc5d1cf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.68.jar",
          "url": "classpath-utils-0.0.0.68.jar",
          "size": 2930,
          "sha512": "f07f6f08cb999984ad23aec2196b6ff2a0795d82d865a6dae3bb33d1288654316d0ed1641395b9853b400dddc803b8de6bae66d33847e31b3f0fb533415a6457",
          "sha256": "ffad5687cc57b3558217e7c941b5c5ad00ba39165b55e0a923ae0aec512cb815",
          "sha1": "b55a7cece87704c40a96bc00cec912b6be0f1343",
          "md5": "255bcaec0aa50b37e2f27a52bc5d1cf0"
        }
      ]
    }
  ]
}
