{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7xxns67nsvewfpuupao4xeuumy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.71.jar",
          "url": "risk-review-plugin-0.0.0.71.jar",
          "size": 3744,
          "sha512": "fffdb117af041039c96d84b75914a79374c7a4b654a8411a0dee230d159aecaef7961d191188787870a9a8d982afac71eddca99e3a1a7657cece9cfd910c468b",
          "sha256": "73abd928fa5a61d9a910d4729067be03675ab56ec0d3738b61c50dcf83e727ac",
          "sha1": "31e12d15cbd143c158f29dd1d7ddd14e06874a5c",
          "md5": "f45b94abf8c8cb0253e4609dcac493a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.71"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.71"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.71"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.71"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.71.jar",
          "url": "risk-review-plugin-0.0.0.71.jar",
          "size": 3744,
          "sha512": "fffdb117af041039c96d84b75914a79374c7a4b654a8411a0dee230d159aecaef7961d191188787870a9a8d982afac71eddca99e3a1a7657cece9cfd910c468b",
          "sha256": "73abd928fa5a61d9a910d4729067be03675ab56ec0d3738b61c50dcf83e727ac",
          "sha1": "31e12d15cbd143c158f29dd1d7ddd14e06874a5c",
          "md5": "f45b94abf8c8cb0253e4609dcac493a4"
        }
      ]
    }
  ]
}
