{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.70.jar",
          "url": "risk-management-plugin-0.0.0.70.jar",
          "size": 7335,
          "sha512": "c127ec9a1c273a2ccd167bc645e2f4f30dbd8ce0b368f34bf77b15a74c470cd2cdc65f596d1779e1aceb411d014bd6e1a48719e3b04e3fbc46f047e43c335603",
          "sha256": "5a1aa78eeba73b03cf9bc9cade859154fd7dedf477b9b7add35efd24661198f1",
          "sha1": "4e4c71ec1793b314c49802f94cd3ef4abd36d9c6",
          "md5": "f706fab6a2e8082dccb689c942f08976"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.70.jar",
          "url": "risk-management-plugin-0.0.0.70.jar",
          "size": 7335,
          "sha512": "c127ec9a1c273a2ccd167bc645e2f4f30dbd8ce0b368f34bf77b15a74c470cd2cdc65f596d1779e1aceb411d014bd6e1a48719e3b04e3fbc46f047e43c335603",
          "sha256": "5a1aa78eeba73b03cf9bc9cade859154fd7dedf477b9b7add35efd24661198f1",
          "sha1": "4e4c71ec1793b314c49802f94cd3ef4abd36d9c6",
          "md5": "f706fab6a2e8082dccb689c942f08976"
        }
      ]
    }
  ]
}
