{
  "formatVersion": "1.1",
  "component": {
    "group": "gradle.plugin.setools",
    "module": "meetings-plugin",
    "version": "0.0.0.341",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.341.jar",
          "url": "meetings-plugin-0.0.0.341.jar",
          "size": 5625,
          "sha512": "489a8513b1ee4a9654813fa37fcea862e584ac582d109d0296252215c65a7f02225790420d71c96137dc06667ac70a50f40d600015c55b2425f16613f4d02b9e",
          "sha256": "2df8827ff5eb642946de09fdc35dc99b3d61f60daae5c1a2ac40736f3d043a8a",
          "sha1": "c237422deed27c925ccf4190542d581b96b85fab",
          "md5": "e31b779ef5e794eabb9a3de52c0db152"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "2.25.0"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.341.jar",
          "url": "meetings-plugin-0.0.0.341.jar",
          "size": 5625,
          "sha512": "489a8513b1ee4a9654813fa37fcea862e584ac582d109d0296252215c65a7f02225790420d71c96137dc06667ac70a50f40d600015c55b2425f16613f4d02b9e",
          "sha256": "2df8827ff5eb642946de09fdc35dc99b3d61f60daae5c1a2ac40736f3d043a8a",
          "sha1": "c237422deed27c925ccf4190542d581b96b85fab",
          "md5": "e31b779ef5e794eabb9a3de52c0db152"
        }
      ]
    }
  ]
}
