{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91676,
          "sha512": "b5e601216fca11e1dc873c7bb284028b23c7eb1eaf7e2b896476064a5a02bc7c2ce1a302d86beeb96c6b3c079e30104d6c4f25d6a56b36b243476c83d2cb13bb",
          "sha256": "12c7120379396fedd0b574a50718ed2444d05a4345a005bcbb6c9ed2352c8f",
          "sha1": "58e42975b6981de5d457084b5abbb46d18b28f0c",
          "md5": "a8c396b9bd60693c2002b6dc86815df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91676,
          "sha512": "b5e601216fca11e1dc873c7bb284028b23c7eb1eaf7e2b896476064a5a02bc7c2ce1a302d86beeb96c6b3c079e30104d6c4f25d6a56b36b243476c83d2cb13bb",
          "sha256": "12c7120379396fedd0b574a50718ed2444d05a4345a005bcbb6c9ed2352c8f",
          "sha1": "58e42975b6981de5d457084b5abbb46d18b28f0c",
          "md5": "a8c396b9bd60693c2002b6dc86815df5"
        }
      ]
    }
  ]
}
