{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91587,
          "sha512": "bcadbc33127d0418db89772b0dc06ce673927f7c9f15b794961bc30367ade200a5e023d2a6d409bfc71fef52c336d8784f88a7bb2ad5c2a7e9b7b61907f2dd63",
          "sha256": "c3f3a596c6b4618b3e5f963aa1c070384e9d19bb8c148e82341809f464d05993",
          "sha1": "96395ccb685dd365710b68407c55b2fcd8e55413",
          "md5": "e4104ab6c7c5f09010151aa8b344fade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91587,
          "sha512": "bcadbc33127d0418db89772b0dc06ce673927f7c9f15b794961bc30367ade200a5e023d2a6d409bfc71fef52c336d8784f88a7bb2ad5c2a7e9b7b61907f2dd63",
          "sha256": "c3f3a596c6b4618b3e5f963aa1c070384e9d19bb8c148e82341809f464d05993",
          "sha1": "96395ccb685dd365710b68407c55b2fcd8e55413",
          "md5": "e4104ab6c7c5f09010151aa8b344fade"
        }
      ]
    }
  ]
}
