{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91587,
          "sha512": "abd992fff4eaf4c2135a00e24d787a626453239d62cc2b9e2f5dd555ab08f143afa1ebc2ed3b9c2de456a98f0c55ca9d4d3a46578a8caa5598f59c00b025e17c",
          "sha256": "5383112f32c4fd004e566b58af4e8c477cd3bcd16c045bddfb6525c1c1d442e4",
          "sha1": "e75a81baf7e9d479787603adb2f11ba272ddcaf7",
          "md5": "1ab232f7076a449e748d575479a4609"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.68.jar",
          "size": 91587,
          "sha512": "abd992fff4eaf4c2135a00e24d787a626453239d62cc2b9e2f5dd555ab08f143afa1ebc2ed3b9c2de456a98f0c55ca9d4d3a46578a8caa5598f59c00b025e17c",
          "sha256": "5383112f32c4fd004e566b58af4e8c477cd3bcd16c045bddfb6525c1c1d442e4",
          "sha1": "e75a81baf7e9d479787603adb2f11ba272ddcaf7",
          "md5": "1ab232f7076a449e748d575479a4609"
        }
      ]
    }
  ]
}
