{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "boct5krlmzgqdadpxux4vy4nfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "8bdf3dfaabaee329d87f4ea03fbf74ee2f1b40b5b2ad5054b3b830f40f0fb1ac9573dc696779f93503a891c9dddfc75f638c9482c7fb3ee97c6489ca7ed85d95",
          "sha256": "a3b4bffb4b52c72a6d9173e106c9a2083183621f23aad30bfd7d696493ac8331",
          "sha1": "c7c84e3ee0d7dc2f5e6665f47240a90d616fbd13",
          "md5": "c6113e8a5caf006a8476b50cec950eae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "8bdf3dfaabaee329d87f4ea03fbf74ee2f1b40b5b2ad5054b3b830f40f0fb1ac9573dc696779f93503a891c9dddfc75f638c9482c7fb3ee97c6489ca7ed85d95",
          "sha256": "a3b4bffb4b52c72a6d9173e106c9a2083183621f23aad30bfd7d696493ac8331",
          "sha1": "c7c84e3ee0d7dc2f5e6665f47240a90d616fbd13",
          "md5": "c6113e8a5caf006a8476b50cec950eae"
        }
      ]
    }
  ]
}
