{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "fb9afceba50f7f17e86388403e7b5c28933ae5035825dedae2fde474c8b5640098edd151c5ab578449d72651572f347f485170969b678194063331ecd03462af",
          "sha256": "d8aae5e2bdaa3c4503df55bde4682c3538d4bf70996a927cbaa8f4d25fde203a",
          "sha1": "f7fae658f735c13ef9570bebd2e1527d3081f22f",
          "md5": "df07de257fee48848c201f9fad7381bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "fb9afceba50f7f17e86388403e7b5c28933ae5035825dedae2fde474c8b5640098edd151c5ab578449d72651572f347f485170969b678194063331ecd03462af",
          "sha256": "d8aae5e2bdaa3c4503df55bde4682c3538d4bf70996a927cbaa8f4d25fde203a",
          "sha1": "f7fae658f735c13ef9570bebd2e1527d3081f22f",
          "md5": "df07de257fee48848c201f9fad7381bf"
        }
      ]
    }
  ]
}
