{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "c068e49b9605b942e8eefb339840a888a92ade63137967f762f01d292ec8404aa3e4ab57124bb596c3eb8c459a881a7999e5879417ee622ce9ebee11d18cb2d2",
          "sha256": "e5a7ae5f235f96bdf6ecaff35abd41100df16a445d597559562755a7a694be30",
          "sha1": "e0070deab68d96468d46c298c4f6358c6e01986a",
          "md5": "78a8b0146d7dd659e818f336e6689f2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.69.jar",
          "url": "sysml14-api-0.0.0.69.jar",
          "size": 4848,
          "sha512": "c068e49b9605b942e8eefb339840a888a92ade63137967f762f01d292ec8404aa3e4ab57124bb596c3eb8c459a881a7999e5879417ee622ce9ebee11d18cb2d2",
          "sha256": "e5a7ae5f235f96bdf6ecaff35abd41100df16a445d597559562755a7a694be30",
          "sha1": "e0070deab68d96468d46c298c4f6358c6e01986a",
          "md5": "78a8b0146d7dd659e818f336e6689f2f"
        }
      ]
    }
  ]
}
