{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.69.jar",
          "url": "risk-review-plugin-0.0.0.69.jar",
          "size": 3744,
          "sha512": "490bed0171ce3cec48805e930abb180c8ebb6e6466a67b07ddb5e18c56711a511c65f7a7f469bb754ae31b24f93553ef1ab7be7cfa8fc619a1efb3a026e115c2",
          "sha256": "516f7a6c3ba946805839afb3835672ffe904f18170d6f456b6059a45e7c08180",
          "sha1": "93dcd7f10c93cbe4218a8e0eaa6eca153a0b94db",
          "md5": "c9e6eb1aa30efd6e95dda35cd4cb196d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.69.jar",
          "url": "risk-review-plugin-0.0.0.69.jar",
          "size": 3744,
          "sha512": "490bed0171ce3cec48805e930abb180c8ebb6e6466a67b07ddb5e18c56711a511c65f7a7f469bb754ae31b24f93553ef1ab7be7cfa8fc619a1efb3a026e115c2",
          "sha256": "516f7a6c3ba946805839afb3835672ffe904f18170d6f456b6059a45e7c08180",
          "sha1": "93dcd7f10c93cbe4218a8e0eaa6eca153a0b94db",
          "md5": "c9e6eb1aa30efd6e95dda35cd4cb196d"
        }
      ]
    }
  ]
}
