{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-review-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.69.jar",
          "url": "risk-review-plugin-0.0.0.69.jar",
          "size": 3744,
          "sha512": "db68303dc41b7c4ee74715350eecbfa5bb80165fb5f97cc715350c1f44f4289c658df5aa32a4035b59882f08878daa9ee9f6076106b59bb83601feb2a895b3f1",
          "sha256": "451491301ee3773162cac646f677edc953c039f9919f32beecca6d51f678be72",
          "sha1": "d54b11122d4c697f73271334e66c3a47f365051c",
          "md5": "8cac9c52c68d443018ba42f748fbc98b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.69"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "risk-review-plugin-0.0.0.69.jar",
          "url": "risk-review-plugin-0.0.0.69.jar",
          "size": 3744,
          "sha512": "db68303dc41b7c4ee74715350eecbfa5bb80165fb5f97cc715350c1f44f4289c658df5aa32a4035b59882f08878daa9ee9f6076106b59bb83601feb2a895b3f1",
          "sha256": "451491301ee3773162cac646f677edc953c039f9919f32beecca6d51f678be72",
          "sha1": "d54b11122d4c697f73271334e66c3a47f365051c",
          "md5": "8cac9c52c68d443018ba42f748fbc98b"
        }
      ]
    }
  ]
}
