{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "59da116625cced50c4194a506f51fa51192671eb83b3cd09b6d3afbada6d4e30ea553e7ec23bc9c96ce0708870b9ac6ab5c6027ccf52909053dc9902dfee54aa",
          "sha256": "b9f2de2ca827762fa44bad9abcbeef79524891ebb0c25ec5d6b91236eba0dbd2",
          "sha1": "118f3ee03916ad7c72c4a51c3298d17fd5fb2416",
          "md5": "3d852bb66e8a54fbe7f95b3b7b47c72c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "59da116625cced50c4194a506f51fa51192671eb83b3cd09b6d3afbada6d4e30ea553e7ec23bc9c96ce0708870b9ac6ab5c6027ccf52909053dc9902dfee54aa",
          "sha256": "b9f2de2ca827762fa44bad9abcbeef79524891ebb0c25ec5d6b91236eba0dbd2",
          "sha1": "118f3ee03916ad7c72c4a51c3298d17fd5fb2416",
          "md5": "3d852bb66e8a54fbe7f95b3b7b47c72c"
        }
      ]
    }
  ]
}
