{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "ee66fc2b255209e42ce936331c59721942f67b55eb811b9df3ca93e8f82e4231dd138ae6189261439d0c3636f3f7731dae482e1325a7cc667be7b164878fbec2",
          "sha256": "e196a13d1e5e9af847726acad0125e6fc686b2449f75815c4af46a01fcfc053f",
          "sha1": "5a4005db745065066589c54a8b57991aa3ef6456",
          "md5": "52142bca0142b96742e703dbae30ff46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "ee66fc2b255209e42ce936331c59721942f67b55eb811b9df3ca93e8f82e4231dd138ae6189261439d0c3636f3f7731dae482e1325a7cc667be7b164878fbec2",
          "sha256": "e196a13d1e5e9af847726acad0125e6fc686b2449f75815c4af46a01fcfc053f",
          "sha1": "5a4005db745065066589c54a8b57991aa3ef6456",
          "md5": "52142bca0142b96742e703dbae30ff46"
        }
      ]
    }
  ]
}
