{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "193e8257db480be60636180e5cbab20c5a33c4af3ac46701db572291c5717926db70dca36beccae3d2143895d51f235204eaa3d8e81d24e14f9e3c89c9e9a9bd",
          "sha256": "d6f1d35858ab46f40472b3c988c1c9456b66df730d863bdb1d468a6c130e715b",
          "sha1": "d17405f36e65aacf62c7afe351d99f05346126aa",
          "md5": "59d8ccb8f52e015bdb3a4be391da307d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        }
      ],
      "files": [
        {
          "name": "uml-api-0.0.0.68.jar",
          "url": "uml-api-0.0.0.68.jar",
          "size": 4307,
          "sha512": "193e8257db480be60636180e5cbab20c5a33c4af3ac46701db572291c5717926db70dca36beccae3d2143895d51f235204eaa3d8e81d24e14f9e3c89c9e9a9bd",
          "sha256": "d6f1d35858ab46f40472b3c988c1c9456b66df730d863bdb1d468a6c130e715b",
          "sha1": "d17405f36e65aacf62c7afe351d99f05346126aa",
          "md5": "59d8ccb8f52e015bdb3a4be391da307d"
        }
      ]
    }
  ]
}
