{
  "formatVersion": "1.1",
  "component": {
    "group": "setools.api",
    "module": "gradle-utils",
    "version": "0.0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lupzqluggrfuzcxzb2mtgagviy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradle-utils-0.0.0.38.jar",
          "url": "gradle-utils-0.0.0.38.jar",
          "size": 1256,
          "sha512": "c250753097d989de92d1f1428c0717fbda89e0af4493e6a65f963e3b8c923d16812d376a886b29616a2fb7ced1071db6d8e2aa532993d439e66fd8f728b4a1a4",
          "sha256": "bd9a73bad555e2ef9936dee60134e377cf5e541a0e0a7b7f2b6da326f718f6d8",
          "sha1": "4e5b8128168be04abd67a5d6553aef1d2a827355",
          "md5": "5af1085f566a4a6964ebcce86b5b508c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-utils-0.0.0.38.jar",
          "url": "gradle-utils-0.0.0.38.jar",
          "size": 1256,
          "sha512": "c250753097d989de92d1f1428c0717fbda89e0af4493e6a65f963e3b8c923d16812d376a886b29616a2fb7ced1071db6d8e2aa532993d439e66fd8f728b4a1a4",
          "sha256": "bd9a73bad555e2ef9936dee60134e377cf5e541a0e0a7b7f2b6da326f718f6d8",
          "sha1": "4e5b8128168be04abd67a5d6553aef1d2a827355",
          "md5": "5af1085f566a4a6964ebcce86b5b508c"
        }
      ]
    }
  ]
}
