{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.68.jar",
          "url": "risk-management-plugin-0.0.0.68.jar",
          "size": 7335,
          "sha512": "4c186a2ab923dcbc9b6de7ebe9a661f3a758caed83e949d27087d8fb081ee3463f964ec48753f702222d93b61fbc572251b6712895faccd4e5a8820d3c4a0796",
          "sha256": "b7522ed4beb23ca666437584c3ecf22d24c9a1c7ee8b8dd7c5c8e76e5f37ccad",
          "sha1": "dac028df1835651fb6e8f280747f5a86d30d9288",
          "md5": "9511d58da70dae180d61c88f74c9f978"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.68.jar",
          "url": "risk-management-plugin-0.0.0.68.jar",
          "size": 7335,
          "sha512": "4c186a2ab923dcbc9b6de7ebe9a661f3a758caed83e949d27087d8fb081ee3463f964ec48753f702222d93b61fbc572251b6712895faccd4e5a8820d3c4a0796",
          "sha256": "b7522ed4beb23ca666437584c3ecf22d24c9a1c7ee8b8dd7c5c8e76e5f37ccad",
          "sha1": "dac028df1835651fb6e8f280747f5a86d30d9288",
          "md5": "9511d58da70dae180d61c88f74c9f978"
        }
      ]
    }
  ]
}
