{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-management-plugin",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.68.jar",
          "url": "risk-management-plugin-0.0.0.68.jar",
          "size": 7335,
          "sha512": "f072f52867dacdac94f8d0e1482ae20a91b5a1481aa92a88c2e4c1f2e88afdb6086209d2da9902b39dd3a021c9ae608683f9d64aad2367e03b887149ac94ce7c",
          "sha256": "39bcc5b89938dcfcb2d4c056a21057302560373886bf212dd8195a56dbcd8770",
          "sha1": "d45bba9469d0237252bd3eabcb217238e9ae4411",
          "md5": "92ec2c438b5ef622203e99107d4a4ecd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.68"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20190722"
          }
        }
      ],
      "files": [
        {
          "name": "risk-management-plugin-0.0.0.68.jar",
          "url": "risk-management-plugin-0.0.0.68.jar",
          "size": 7335,
          "sha512": "f072f52867dacdac94f8d0e1482ae20a91b5a1481aa92a88c2e4c1f2e88afdb6086209d2da9902b39dd3a021c9ae608683f9d64aad2367e03b887149ac94ce7c",
          "sha256": "39bcc5b89938dcfcb2d4c056a21057302560373886bf212dd8195a56dbcd8770",
          "sha1": "d45bba9469d0237252bd3eabcb217238e9ae4411",
          "md5": "92ec2c438b5ef622203e99107d4a4ecd"
        }
      ]
    }
  ]
}
