{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.72",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "f56mhqhau5gfxeik3nsjtzaqx4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.72"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.72.jar",
          "url": "sysml16-api-0.0.0.72.jar",
          "size": 4846,
          "sha512": "6826e2603c49a47c9518f1331e9c8ee94eea879d26eacde11d5b4f25cd0bf95210cbaa9eb03a408bcb023583495bf98151fb89dc42e8f238a1fa92dc05785c3c",
          "sha256": "e8d5570ee3349037dc1e0db4fa91ab4d5f5c07605cc5ca0a051db62ebe332e35",
          "sha1": "2a84b8409b7416b61bdd082082e58e5c7407b2a",
          "md5": "38fb9be4b7c99edb2e37f3935b810f92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.72"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.72.jar",
          "url": "sysml16-api-0.0.0.72.jar",
          "size": 4846,
          "sha512": "6826e2603c49a47c9518f1331e9c8ee94eea879d26eacde11d5b4f25cd0bf95210cbaa9eb03a408bcb023583495bf98151fb89dc42e8f238a1fa92dc05785c3c",
          "sha256": "e8d5570ee3349037dc1e0db4fa91ab4d5f5c07605cc5ca0a051db62ebe332e35",
          "sha1": "2a84b8409b7416b61bdd082082e58e5c7407b2a",
          "md5": "38fb9be4b7c99edb2e37f3935b810f92"
        }
      ]
    }
  ]
}
