{
  "formatVersion": "1.1",
  "component": {
    "group": "setools.api",
    "module": "gradle-test-api",
    "version": "0.0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "lupzqluggrfuzcxzb2mtgagviy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine"
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-test-api-0.0.0.38.jar",
          "url": "gradle-test-api-0.0.0.38.jar",
          "size": 3705,
          "sha512": "fb738ab06912f698bf76ed6852761cf6c0eba0446bd82e6c24fbff6accf9fb276dd888df73cbe2a6f717ec449238b51f30a7e51056e4578d0726a613fe68b307",
          "sha256": "562e4abebfe66841187abcc2ec12de00ed6073532631de360011c6fc02fab5ee",
          "sha1": "c80b5ac01dc789f49b7e01973ac6d1b4c5284880",
          "md5": "6c34a305be1719f6294aae8dec5b0ba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.6.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine"
        }
      ],
      "files": [
        {
          "name": "gradle-test-api-0.0.0.38.jar",
          "url": "gradle-test-api-0.0.0.38.jar",
          "size": 3705,
          "sha512": "fb738ab06912f698bf76ed6852761cf6c0eba0446bd82e6c24fbff6accf9fb276dd888df73cbe2a6f717ec449238b51f30a7e51056e4578d0726a613fe68b307",
          "sha256": "562e4abebfe66841187abcc2ec12de00ed6073532631de360011c6fc02fab5ee",
          "sha1": "c80b5ac01dc789f49b7e01973ac6d1b4c5284880",
          "md5": "6c34a305be1719f6294aae8dec5b0ba9"
        }
      ]
    }
  ]
}
