{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "ooxml-risk-review-plugin",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.70.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.70.jar",
          "size": 91587,
          "sha512": "e885d09140b34d26b45a7d06b7e2db56d2a2d265c963bcb90be93d8cd68a33afa220f02dfc860d085d03dfafd7f782b72c1d7522f638dee85b9aa121e802bd4c",
          "sha256": "d16d2c8ccd54993459e03934c6bf143ef33a5b6e04cf83c49517e0c30808766d",
          "sha1": "e72e6b6679d0bec340f1ce091253930cae12f8ad",
          "md5": "6b78a2acb163e4145039be994a1782ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "risk-base-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "risk-api",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "uml-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "risk-review-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "setools",
          "module": "meetings-plugin",
          "version": {
            "requires": "0.0.0.70"
          }
        },
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ooxml-risk-review-plugin-0.0.0.70.jar",
          "url": "ooxml-risk-review-plugin-0.0.0.70.jar",
          "size": 91587,
          "sha512": "e885d09140b34d26b45a7d06b7e2db56d2a2d265c963bcb90be93d8cd68a33afa220f02dfc860d085d03dfafd7f782b72c1d7522f638dee85b9aa121e802bd4c",
          "sha256": "d16d2c8ccd54993459e03934c6bf143ef33a5b6e04cf83c49517e0c30808766d",
          "sha1": "e72e6b6679d0bec340f1ce091253930cae12f8ad",
          "md5": "6b78a2acb163e4145039be994a1782ad"
        }
      ]
    }
  ]
}
