{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.69.jar",
          "url": "classpath-utils-0.0.0.69.jar",
          "size": 2930,
          "sha512": "28e19494874d71cb2f7029d6dfb0f5987d2c33e85bcca20404fa0465ff1537da20e4a25da9d280d18caaf82cd25e0c9fca1cbe6d203cd9662ade011704b8e296",
          "sha256": "98e25179c3d84951c0de5e0dfd19bb830fa9a9db9279d3fe9b2e7e72e5a52a09",
          "sha1": "a2fcc4af5982d9ccfda8d4db4211ae8082a19463",
          "md5": "313315842a005580744195b3263168c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.69.jar",
          "url": "classpath-utils-0.0.0.69.jar",
          "size": 2930,
          "sha512": "28e19494874d71cb2f7029d6dfb0f5987d2c33e85bcca20404fa0465ff1537da20e4a25da9d280d18caaf82cd25e0c9fca1cbe6d203cd9662ade011704b8e296",
          "sha256": "98e25179c3d84951c0de5e0dfd19bb830fa9a9db9279d3fe9b2e7e72e5a52a09",
          "sha1": "a2fcc4af5982d9ccfda8d4db4211ae8082a19463",
          "md5": "313315842a005580744195b3263168c0"
        }
      ]
    }
  ]
}
