{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "classpath-utils",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.69.jar",
          "url": "classpath-utils-0.0.0.69.jar",
          "size": 2930,
          "sha512": "a2213331860de9b1450f44d48c79c9fdb434ee07f03119a9b71f18a453f58f110f7170c6a714d89a0b64fecc11a37f978b232e6e5e8b4f39a33d9eb42eaee6a1",
          "sha256": "bc21f8fd3d365f30bd0ddcdf56cc70f91b066443c63b404552dcec6e3774081a",
          "sha1": "174409566740967ceec494df670324d08daf52a9",
          "md5": "899c9fe343ceade6cd53a603e78553e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "classpath-utils-0.0.0.69.jar",
          "url": "classpath-utils-0.0.0.69.jar",
          "size": 2930,
          "sha512": "a2213331860de9b1450f44d48c79c9fdb434ee07f03119a9b71f18a453f58f110f7170c6a714d89a0b64fecc11a37f978b232e6e5e8b4f39a33d9eb42eaee6a1",
          "sha256": "bc21f8fd3d365f30bd0ddcdf56cc70f91b066443c63b404552dcec6e3774081a",
          "sha1": "174409566740967ceec494df670324d08daf52a9",
          "md5": "899c9fe343ceade6cd53a603e78553e2"
        }
      ]
    }
  ]
}
