{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "smr5unupa5drrjbz25yk6ludie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.50"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.50.jar",
          "url": "risk-api-0.0.0.50.jar",
          "size": 44576,
          "sha512": "3343c4761a77c1b71dab1314771f5aac7c19e51a689e7ae3a763dc510981850edd6f756a674de4b7f3a34b5768b2d9a42eb1e9b60f193e6b3d7c4814e6f9aa20",
          "sha256": "69df485ba40df776a5b995dd853c80d605b988b6c20a9bfb900eeb3dcfe879d6",
          "sha1": "cead8857eb5598c78cf9ecdef365259a92ed1260",
          "md5": "4062904bee4b571c2e542f64ef8064c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.50"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.50.jar",
          "url": "risk-api-0.0.0.50.jar",
          "size": 44576,
          "sha512": "3343c4761a77c1b71dab1314771f5aac7c19e51a689e7ae3a763dc510981850edd6f756a674de4b7f3a34b5768b2d9a42eb1e9b60f193e6b3d7c4814e6f9aa20",
          "sha256": "69df485ba40df776a5b995dd853c80d605b988b6c20a9bfb900eeb3dcfe879d6",
          "sha1": "cead8857eb5598c78cf9ecdef365259a92ed1260",
          "md5": "4062904bee4b571c2e542f64ef8064c0"
        }
      ]
    }
  ]
}
