{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "boct5krlmzgqdadpxux4vy4nfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "bc2a517c36e5792a9c204ea58b7086c0223603ecd6309d3176a009125a85b2a8f9d991df3edb5d3693b712452899f160e086030939d5c3414406c18da07e046a",
          "sha256": "12e6f2162a3b1a43ee16427ce9f0299c59f610f5c0719d4758aa2502d064cec8",
          "sha1": "fcb4ffdb01ef9b0ab08c09e7008481fd07a0c403",
          "md5": "ebb635e0186cb7e0e4b2d8bcc20ebf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "bc2a517c36e5792a9c204ea58b7086c0223603ecd6309d3176a009125a85b2a8f9d991df3edb5d3693b712452899f160e086030939d5c3414406c18da07e046a",
          "sha256": "12e6f2162a3b1a43ee16427ce9f0299c59f610f5c0719d4758aa2502d064cec8",
          "sha1": "fcb4ffdb01ef9b0ab08c09e7008481fd07a0c403",
          "md5": "ebb635e0186cb7e0e4b2d8bcc20ebf6"
        }
      ]
    }
  ]
}
