{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "6011941f0422535851811d03be3ca3f11adfa803fe4fcdcff1aeae1543ebcec8c977d834a5cdbe5ce9a196fc64720a2d4eb0e8a88719e016b794ea4c129f6024",
          "sha256": "b4a4f79a12838aa052d8361593020ed72f1c3482420075c3e5f8b7c20c57e66a",
          "sha1": "7afa37efed9fae3df122d153b13f397500bf9cfe",
          "md5": "2da8c81dd2f1d7bae3af7670bd25e518"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "6011941f0422535851811d03be3ca3f11adfa803fe4fcdcff1aeae1543ebcec8c977d834a5cdbe5ce9a196fc64720a2d4eb0e8a88719e016b794ea4c129f6024",
          "sha256": "b4a4f79a12838aa052d8361593020ed72f1c3482420075c3e5f8b7c20c57e66a",
          "sha1": "7afa37efed9fae3df122d153b13f397500bf9cfe",
          "md5": "2da8c81dd2f1d7bae3af7670bd25e518"
        }
      ]
    }
  ]
}
