{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "risk-api",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "4b5df7cac472f48d354dc7f664e2c885408c6a14f9beb8145be3334f3da78a75ea3e2244abcc1e17392474a3de8e1726a4b2a966bc3d8e335e0f0d0a4ce0aa8",
          "sha256": "b2bbe785c0fe7f6a4c35a6dc6cd540deedf2e2349e2b514fc376cd958655c284",
          "sha1": "b69dd12fdb0e1afe498d0cef0e68f3aa28eec117",
          "md5": "56b772fb553b84a0b49f1bf2cb18ec84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.69"
          }
        }
      ],
      "files": [
        {
          "name": "risk-api-0.0.0.69.jar",
          "url": "risk-api-0.0.0.69.jar",
          "size": 52213,
          "sha512": "4b5df7cac472f48d354dc7f664e2c885408c6a14f9beb8145be3334f3da78a75ea3e2244abcc1e17392474a3de8e1726a4b2a966bc3d8e335e0f0d0a4ce0aa8",
          "sha256": "b2bbe785c0fe7f6a4c35a6dc6cd540deedf2e2349e2b514fc376cd958655c284",
          "sha1": "b69dd12fdb0e1afe498d0cef0e68f3aa28eec117",
          "md5": "56b772fb553b84a0b49f1bf2cb18ec84"
        }
      ]
    }
  ]
}
