{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "uml-plugin",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uml-plugin-0.0.0.70.jar",
          "url": "uml-plugin-0.0.0.70.jar",
          "size": 6132,
          "sha512": "b7312b86d3d67efe7c4a47098c96d3ec9b78976955c9b76c0b68f3923f88a9feb4ac988efc0f9f39c0282de43a479f96b7227d1e697d8c28354e03e89dcc6fbf",
          "sha256": "852b1210c5d3e505b0fdc9beda0c9189f8ca5874dc6a57e5c33eef70ec92df05",
          "sha1": "93efe0a2bf225e7e5948254cce084211dc368c5c",
          "md5": "1531b38940c3a2bdbfb7435dd815a288"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.70"
          }
        }
      ],
      "files": [
        {
          "name": "uml-plugin-0.0.0.70.jar",
          "url": "uml-plugin-0.0.0.70.jar",
          "size": 6132,
          "sha512": "b7312b86d3d67efe7c4a47098c96d3ec9b78976955c9b76c0b68f3923f88a9feb4ac988efc0f9f39c0282de43a479f96b7227d1e697d8c28354e03e89dcc6fbf",
          "sha256": "852b1210c5d3e505b0fdc9beda0c9189f8ca5874dc6a57e5c33eef70ec92df05",
          "sha1": "93efe0a2bf225e7e5948254cce084211dc368c5c",
          "md5": "1531b38940c3a2bdbfb7435dd815a288"
        }
      ]
    }
  ]
}
