{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4oj7d3ecvbdarest4xovyr6lsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.69.jar",
          "url": "meetings-plugin-0.0.0.69.jar",
          "size": 92108,
          "sha512": "49544242d2c2c4f2783d0746b260c1bb9fe7bd5fc41f0e5365fa6a4634e2d0ab05fa78b6935a25380af61ed885fcecb8b485fef0541a2e55c611825f88602009",
          "sha256": "8967164aea2021be7e80b2769d4de29b095c39e288a0b2123e4f5c6813d372a7",
          "sha1": "a06479e23550c30e6fd78d92bc84c12c65603bf9",
          "md5": "4ac70e39f4151673529c559a868cddcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.69.jar",
          "url": "meetings-plugin-0.0.0.69.jar",
          "size": 92108,
          "sha512": "49544242d2c2c4f2783d0746b260c1bb9fe7bd5fc41f0e5365fa6a4634e2d0ab05fa78b6935a25380af61ed885fcecb8b485fef0541a2e55c611825f88602009",
          "sha256": "8967164aea2021be7e80b2769d4de29b095c39e288a0b2123e4f5c6813d372a7",
          "sha1": "a06479e23550c30e6fd78d92bc84c12c65603bf9",
          "md5": "4ac70e39f4151673529c559a868cddcd"
        }
      ]
    }
  ]
}
