{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "meetings-plugin",
    "version": "0.0.0.69",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "wv75bp456fai3ibydu3nhdbrbm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "meetings-plugin-0.0.0.69.jar",
          "url": "meetings-plugin-0.0.0.69.jar",
          "size": 92108,
          "sha512": "f9bafbc28b150efc9f1011c6de8739e0f2ba16389c41a54b3ecdfded40de0ec378f8ae2ee4636941416ac0a8d134e0e2afed45ffd4a8aee3862903443079b0be",
          "sha256": "cb81752dbd8923058e6474f08bd55722ec39d319f2322947acdc3b02fb54b326",
          "sha1": "7bef9c847dcf77071dac63c2af3648db40e5b88f",
          "md5": "41cb6190d50ebf08ba5be879091181cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.poi",
          "module": "poi-ooxml",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.8"
          }
        }
      ],
      "files": [
        {
          "name": "meetings-plugin-0.0.0.69.jar",
          "url": "meetings-plugin-0.0.0.69.jar",
          "size": 92108,
          "sha512": "f9bafbc28b150efc9f1011c6de8739e0f2ba16389c41a54b3ecdfded40de0ec378f8ae2ee4636941416ac0a8d134e0e2afed45ffd4a8aee3862903443079b0be",
          "sha256": "cb81752dbd8923058e6474f08bd55722ec39d319f2322947acdc3b02fb54b326",
          "sha1": "7bef9c847dcf77071dac63c2af3648db40e5b88f",
          "md5": "41cb6190d50ebf08ba5be879091181cf"
        }
      ]
    }
  ]
}
