{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "brn73jfvojbm5jc4naynp4txka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "a6ac421f7630e9d8e6cd32d12f392f362fcae64b2c63a5b45eca9919af3c17d1bb6c8074424739264138f98f5e55ff5f56181b91290d7d66c7ae291626c317d4",
          "sha256": "d4eb0938dfc0740af03fa83d7fbbea8a9879e9fe3daeea7de875ce1b0b663e69",
          "sha1": "283cfead4cb96a5936fab1cd24fb75a0700a8070",
          "md5": "b6da654c4e3c82b190f850b9d6cc13c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "a6ac421f7630e9d8e6cd32d12f392f362fcae64b2c63a5b45eca9919af3c17d1bb6c8074424739264138f98f5e55ff5f56181b91290d7d66c7ae291626c317d4",
          "sha256": "d4eb0938dfc0740af03fa83d7fbbea8a9879e9fe3daeea7de875ce1b0b663e69",
          "sha1": "283cfead4cb96a5936fab1cd24fb75a0700a8070",
          "md5": "b6da654c4e3c82b190f850b9d6cc13c"
        }
      ]
    }
  ]
}
