{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "d6obrwrtnzdjxafrhbvokvlo6q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "d9a59209057fe593c718379d81e166d645ba5c6b62b4380c0616684c4326823db8d0ec2a8f78e5db00b88027a7a653f33529b3107d4345c80d37bb37ff967da",
          "sha256": "e01aeeb016d02fc067f3e8b7085ee03e6ff26e0aa29bffd9962d7214a75c0db3",
          "sha1": "c932d7796569b66f7ffed500de295f31974c6476",
          "md5": "a90f0d223d53114a1b787e952eac2898"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "d9a59209057fe593c718379d81e166d645ba5c6b62b4380c0616684c4326823db8d0ec2a8f78e5db00b88027a7a653f33529b3107d4345c80d37bb37ff967da",
          "sha256": "e01aeeb016d02fc067f3e8b7085ee03e6ff26e0aa29bffd9962d7214a75c0db3",
          "sha1": "c932d7796569b66f7ffed500de295f31974c6476",
          "md5": "a90f0d223d53114a1b787e952eac2898"
        }
      ]
    }
  ]
}
