{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml16-api",
    "version": "0.0.0.68",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gxes5i6nzrddllljlddy6up76u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "b15e24d5ee4508809d21e9daad123134046d4d61678a2beba347f45f4f5d95ac4435f9a6fe6a7622bdfc8afe758287ba099b19b1b05d9237b90ffb705579a281",
          "sha256": "d1249f49243af0cae21c544a9876fbdf33ff4a8269cd46b5d08ef0ff93f5fa52",
          "sha1": "a2b5eac2729624744fec18d66a22f342db72e4a9",
          "md5": "6a34a7ffa688378c4bba7e9aa2dc6856"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml16",
          "version": {
            "requires": "[1.0.0,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.68"
          }
        }
      ],
      "files": [
        {
          "name": "sysml16-api-0.0.0.68.jar",
          "url": "sysml16-api-0.0.0.68.jar",
          "size": 4846,
          "sha512": "b15e24d5ee4508809d21e9daad123134046d4d61678a2beba347f45f4f5d95ac4435f9a6fe6a7622bdfc8afe758287ba099b19b1b05d9237b90ffb705579a281",
          "sha256": "d1249f49243af0cae21c544a9876fbdf33ff4a8269cd46b5d08ef0ff93f5fa52",
          "sha1": "a2b5eac2729624744fec18d66a22f342db72e4a9",
          "md5": "6a34a7ffa688378c4bba7e9aa2dc6856"
        }
      ]
    }
  ]
}
