{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "nb7fnnfetzb5voyogf37xpopge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.70"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.70.jar",
          "url": "sysml14-api-0.0.0.70.jar",
          "size": 4848,
          "sha512": "6cff030f55eb02e8d35d9c26ae48191a31e3ff5a5722b03b9cda6db99996f8339e4acafde9d30e597e6d84d95040156b6356d11b9cfe3222c4016d43d18bdd4b",
          "sha256": "b0a6925384fba5bea565fbe3ba30cdb01f77444dbacf2119782605f138b93a50",
          "sha1": "7dc47c74fdff81a5b095dc624ac1debb1cb3520a",
          "md5": "ec226d2b1c7827496befa5c233845c04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.70"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.70.jar",
          "url": "sysml14-api-0.0.0.70.jar",
          "size": 4848,
          "sha512": "6cff030f55eb02e8d35d9c26ae48191a31e3ff5a5722b03b9cda6db99996f8339e4acafde9d30e597e6d84d95040156b6356d11b9cfe3222c4016d43d18bdd4b",
          "sha256": "b0a6925384fba5bea565fbe3ba30cdb01f77444dbacf2119782605f138b93a50",
          "sha1": "7dc47c74fdff81a5b095dc624ac1debb1cb3520a",
          "md5": "ec226d2b1c7827496befa5c233845c04"
        }
      ]
    }
  ]
}
