{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.70",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "gehbh7oo3fevlhipu7ewq4giua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.70"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.70.jar",
          "url": "sysml14-api-0.0.0.70.jar",
          "size": 4848,
          "sha512": "5efb5263678ba5addcc59e3524ff354313417813fe8cc7056d173ffee6895d664c53bb1dbb949daba69b2483be9b89cbb27308b842aba3753b6932838cd3df5d",
          "sha256": "c54153acb14b4c5c48316be0917d574484dd838214f1e62f1a111c971df61b59",
          "sha1": "dda3f0625f6d0f4df71378c7e5f1be379868027",
          "md5": "2d26406a07abf457fa980029c0fd5e29"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.70"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.70.jar",
          "url": "sysml14-api-0.0.0.70.jar",
          "size": 4848,
          "sha512": "5efb5263678ba5addcc59e3524ff354313417813fe8cc7056d173ffee6895d664c53bb1dbb949daba69b2483be9b89cbb27308b842aba3753b6932838cd3df5d",
          "sha256": "c54153acb14b4c5c48316be0917d574484dd838214f1e62f1a111c971df61b59",
          "sha1": "dda3f0625f6d0f4df71378c7e5f1be379868027",
          "md5": "2d26406a07abf457fa980029c0fd5e29"
        }
      ]
    }
  ]
}
