{
  "formatVersion": "1.1",
  "component": {
    "group": "setools",
    "module": "sysml14-api",
    "version": "0.0.0.71",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7xxns67nsvewfpuupao4xeuumy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.71"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.71.jar",
          "url": "sysml14-api-0.0.0.71.jar",
          "size": 4848,
          "sha512": "69a70edb500081fcc52f3c324866053723d5de4e9e7faac1338086481d771dde312418b3d60637b6cf4334290ac27faafea905753b1e954c201a9bfdc6615a",
          "sha256": "93bc09c2b253ea1f7220e618280fc062679dca879d7eef0c906ce57104b9cecb",
          "sha1": "8ee36bb1a9d226ea4d7dc447cb42aa6353797fae",
          "md5": "6b410cdd97bcdac5e9262bb369ddd94b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.eclipse.emf",
          "module": "org.eclipse.emf.ecore",
          "version": {
            "requires": "[2.18.0,3.0.0)"
          }
        },
        {
          "group": "org.eclipse.uml2",
          "module": "org.eclipse.uml2.uml.resources",
          "version": {
            "requires": "[5.0.0,6.0.0)"
          }
        },
        {
          "group": "org.eclipse.papyrus.sysml",
          "module": "org.eclipse.papyrus.sysml14",
          "version": {
            "requires": "[1.3.200,2.0.0)"
          }
        },
        {
          "group": "setools",
          "module": "uml-api",
          "version": {
            "requires": "0.0.0.71"
          }
        }
      ],
      "files": [
        {
          "name": "sysml14-api-0.0.0.71.jar",
          "url": "sysml14-api-0.0.0.71.jar",
          "size": 4848,
          "sha512": "69a70edb500081fcc52f3c324866053723d5de4e9e7faac1338086481d771dde312418b3d60637b6cf4334290ac27faafea905753b1e954c201a9bfdc6615a",
          "sha256": "93bc09c2b253ea1f7220e618280fc062679dca879d7eef0c906ce57104b9cecb",
          "sha1": "8ee36bb1a9d226ea4d7dc447cb42aa6353797fae",
          "md5": "6b410cdd97bcdac5e9262bb369ddd94b"
        }
      ]
    }
  ]
}
